// Central icon set and repo config for solid-icons-ssr
// Used by both generateFromTemplate.ts and clone-icon-repos.ts

export const iconSetConfigs = [
  {
    name: 'tabler',
    repoUrl: 'https://github.com/tabler/tabler-icons.git',
    gitBranch: 'main',
    svgGlob: 'icons/outline/*.svg',
    componentPrefix: 'Tabler',
    cacheDir: '../.icon-cache/tabler',
    license: 'MIT',
    licenseUrl: 'https://github.com/tabler/tabler-icons/blob/main/LICENSE',
  },
  {
    name: 'heroicons',
    repoUrl: 'https://github.com/tailwindlabs/heroicons.git',
    gitBranch: 'master',
    svgGlob: 'src/24/outline/*.svg',
    componentPrefix: 'Hero',
    cacheDir: '../.icon-cache/heroicons',
    license: 'MIT',
    licenseUrl: 'https://github.com/tailwindlabs/heroicons/blob/master/LICENSE',
  },
  {
    name: 'lucide',
    repoUrl: 'https://github.com/lucide-icons/lucide.git',
    gitBranch: 'main',
    svgGlob: 'icons/*.svg',
    componentPrefix: 'Lucide',
    cacheDir: '../.icon-cache/lucide',
    license: 'ISC',
    licenseUrl: 'https://github.com/lucide-icons/lucide/blob/main/LICENSE',
  },
  {
    name: 'feather',
    repoUrl: 'https://github.com/feathericons/feather.git',
    gitBranch: 'main',
    svgGlob: 'icons/*.svg',
    componentPrefix: 'Feather',
    cacheDir: '../.icon-cache/feather',
    license: 'MIT',
    licenseUrl: 'https://github.com/feathericons/feather/blob/main/LICENSE',
  },
  {
    name: 'bootstrap',
    repoUrl: 'https://github.com/twbs/icons.git',
    gitBranch: 'main',
    svgGlob: 'icons/*.svg',
    componentPrefix: 'Bootstrap',
    cacheDir: '../.icon-cache/bootstrap',
    license: 'MIT',
    licenseUrl: 'https://github.com/twbs/icons/blob/main/LICENSE.md',
  },
  {
    name: 'remix',
    repoUrl: 'https://github.com/Remix-Design/RemixIcon.git',
    gitBranch: 'master',
    svgGlob: 'icons/*.svg',
    componentPrefix: 'Remix',
    cacheDir: '../.icon-cache/remix',
    license: 'Apache-2.0',
    licenseUrl: 'https://github.com/Remix-Design/RemixIcon/blob/master/LICENSE',
  },
  {
    name: 'boxicons',
    repoUrl: 'https://github.com/atisawd/boxicons.git',
    gitBranch: 'master',
    svgGlob: 'svg/regular/*.svg',
    componentPrefix: 'Box',
    cacheDir: '../.icon-cache/boxicons',
    license: 'MIT',
    licenseUrl: 'https://github.com/atisawd/boxicons/blob/master/LICENSE',
  },
  {
    name: 'simpleicons',
    repoUrl: 'https://github.com/simple-icons/simple-icons.git',
    gitBranch: 'develop',
    svgGlob: 'icons/*.svg',
    componentPrefix: 'Simple',
    cacheDir: '../.icon-cache/simpleicons',
    license: 'CC0-1.0',
    licenseUrl: 'https://github.com/simple-icons/simple-icons/blob/develop/LICENSE.md',
  },
  {
    name: 'eva',
    repoUrl: 'https://github.com/akveo/eva-icons.git',
    gitBranch: 'master',
    svgGlob: 'outline/*.svg',
    componentPrefix: 'Eva',
    cacheDir: '../.icon-cache/eva',
    license: 'MIT',
    licenseUrl: 'https://github.com/akveo/eva-icons/blob/master/LICENSE.txt',
  },
  {
    name: 'phosphor',
    repoUrl: 'https://github.com/phosphor-icons/phosphor-icons.git',
    gitBranch: 'master',
    svgGlob: 'packages/phosphor-icons/src/regular/*.svg',
    componentPrefix: 'Phosphor',
    cacheDir: '../.icon-cache/phosphor',
    license: 'MIT',
    licenseUrl: 'https://github.com/phosphor-icons/phosphor-icons/blob/master/LICENSE',
  },
  // Zondicons (MIT)
  {
    name: 'zondicons',
    repoUrl: 'https://github.com/dukestreetstudio/zondicons.git',
    gitBranch: 'master',
    svgGlob: 'src/*.svg',
    componentPrefix: 'Zondicon',
    cacheDir: '../.icon-cache/zondicons',
    license: 'MIT',
    licenseUrl: 'https://github.com/dukestreetstudio/zondicons/blob/master/LICENSE',
  },
  // Ionicons (MIT)
  {
    name: 'ionicons',
    repoUrl: 'https://github.com/ionic-team/ionicons.git',
    gitBranch: 'main',
    svgGlob: 'src/svg/*.svg',
    componentPrefix: 'Ion',
    cacheDir: '../.icon-cache/ionicons',
    license: 'MIT',
    licenseUrl: 'https://github.com/ionic-team/ionicons/blob/main/LICENSE',
  },
  // Codicons (MIT)
  {
    name: 'codicons',
    repoUrl: 'https://github.com/microsoft/vscode-codicons.git',
    gitBranch: 'main',
    svgGlob: 'src/icons/*.svg',
    componentPrefix: 'Codicon',
    cacheDir: '../.icon-cache/codicons',
    license: 'MIT',
    licenseUrl: 'https://github.com/microsoft/vscode-codicons/blob/main/LICENSE',
  },
] as const
