[build]  
  publish = "dist"
  command = "pnpm install --frozen-lockfile && pnpm run build"

[dev]
  command = "pnpm run dev"
  port = 5173


[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--version"
  NODE_OPTIONS = "--max-old-space-size=4096"

[functions]
  directory = "netlify/functions"

[context.production.environment]
  NODE_ENV = "production"
