// AUTO-GENERATED FILE. DO NOT EDIT BY HAND.
// Icon set: fontawesome/regular | License: CC BY 4.0 (CC BY 4.0_URL)
import type { JSX } from 'solid-js'
import type { IconProps } from '..//types'

export function FaRegularAddressBook(props: IconProps): JSX.Element
export function FaRegularAddressCard(props: IconProps): JSX.Element
export function FaRegularBellSlash(props: IconProps): JSX.Element
export function FaRegularBell(props: IconProps): JSX.Element
export function FaRegularBookmark(props: IconProps): JSX.Element
export function FaRegularBuilding(props: IconProps): JSX.Element
export function FaRegularCalendarCheck(props: IconProps): JSX.Element
export function FaRegularCalendarDays(props: IconProps): JSX.Element
export function FaRegularCalendarMinus(props: IconProps): JSX.Element
export function FaRegularCalendarPlus(props: IconProps): JSX.Element
export function FaRegularCalendarXmark(props: IconProps): JSX.Element
export function FaRegularCalendar(props: IconProps): JSX.Element
export function FaRegularChartBar(props: IconProps): JSX.Element
export function FaRegularChessBishop(props: IconProps): JSX.Element
export function FaRegularChessKing(props: IconProps): JSX.Element
export function FaRegularChessKnight(props: IconProps): JSX.Element
export function FaRegularChessPawn(props: IconProps): JSX.Element
export function FaRegularChessQueen(props: IconProps): JSX.Element
export function FaRegularChessRook(props: IconProps): JSX.Element
export function FaRegularCircleCheck(props: IconProps): JSX.Element
export function FaRegularCircleDot(props: IconProps): JSX.Element
export function FaRegularCircleDown(props: IconProps): JSX.Element
export function FaRegularCircleLeft(props: IconProps): JSX.Element
export function FaRegularCirclePause(props: IconProps): JSX.Element
export function FaRegularCirclePlay(props: IconProps): JSX.Element
export function FaRegularCircleQuestion(props: IconProps): JSX.Element
export function FaRegularCircleRight(props: IconProps): JSX.Element
export function FaRegularCircleStop(props: IconProps): JSX.Element
export function FaRegularCircleUp(props: IconProps): JSX.Element
export function FaRegularCircleUser(props: IconProps): JSX.Element
export function FaRegularCircleXmark(props: IconProps): JSX.Element
export function FaRegularCircle(props: IconProps): JSX.Element
export function FaRegularClipboard(props: IconProps): JSX.Element
export function FaRegularClock(props: IconProps): JSX.Element
export function FaRegularClone(props: IconProps): JSX.Element
export function FaRegularClosedCaptioning(props: IconProps): JSX.Element
export function FaRegularCommentDots(props: IconProps): JSX.Element
export function FaRegularComment(props: IconProps): JSX.Element
export function FaRegularComments(props: IconProps): JSX.Element
export function FaRegularCompass(props: IconProps): JSX.Element
export function FaRegularCopy(props: IconProps): JSX.Element
export function FaRegularCopyright(props: IconProps): JSX.Element
export function FaRegularCreditCard(props: IconProps): JSX.Element
export function FaRegularEnvelopeOpen(props: IconProps): JSX.Element
export function FaRegularEnvelope(props: IconProps): JSX.Element
export function FaRegularEyeSlash(props: IconProps): JSX.Element
export function FaRegularEye(props: IconProps): JSX.Element
export function FaRegularFaceAngry(props: IconProps): JSX.Element
export function FaRegularFaceDizzy(props: IconProps): JSX.Element
export function FaRegularFaceFlushed(props: IconProps): JSX.Element
export function FaRegularFaceFrownOpen(props: IconProps): JSX.Element
export function FaRegularFaceFrown(props: IconProps): JSX.Element
export function FaRegularFaceGrimace(props: IconProps): JSX.Element
export function FaRegularFaceGrinBeamSweat(props: IconProps): JSX.Element
export function FaRegularFaceGrinBeam(props: IconProps): JSX.Element
export function FaRegularFaceGrinHearts(props: IconProps): JSX.Element
export function FaRegularFaceGrinSquintTears(props: IconProps): JSX.Element
export function FaRegularFaceGrinSquint(props: IconProps): JSX.Element
export function FaRegularFaceGrinStars(props: IconProps): JSX.Element
export function FaRegularFaceGrinTears(props: IconProps): JSX.Element
export function FaRegularFaceGrinTongueSquint(props: IconProps): JSX.Element
export function FaRegularFaceGrinTongueWink(props: IconProps): JSX.Element
export function FaRegularFaceGrinTongue(props: IconProps): JSX.Element
export function FaRegularFaceGrinWide(props: IconProps): JSX.Element
export function FaRegularFaceGrinWink(props: IconProps): JSX.Element
export function FaRegularFaceGrin(props: IconProps): JSX.Element
export function FaRegularFaceKissBeam(props: IconProps): JSX.Element
export function FaRegularFaceKissWinkHeart(props: IconProps): JSX.Element
export function FaRegularFaceKiss(props: IconProps): JSX.Element
export function FaRegularFaceLaughBeam(props: IconProps): JSX.Element
export function FaRegularFaceLaughSquint(props: IconProps): JSX.Element
export function FaRegularFaceLaughWink(props: IconProps): JSX.Element
export function FaRegularFaceLaugh(props: IconProps): JSX.Element
export function FaRegularFaceMehBlank(props: IconProps): JSX.Element
export function FaRegularFaceMeh(props: IconProps): JSX.Element
export function FaRegularFaceRollingEyes(props: IconProps): JSX.Element
export function FaRegularFaceSadCry(props: IconProps): JSX.Element
export function FaRegularFaceSadTear(props: IconProps): JSX.Element
export function FaRegularFaceSmileBeam(props: IconProps): JSX.Element
export function FaRegularFaceSmileWink(props: IconProps): JSX.Element
export function FaRegularFaceSmile(props: IconProps): JSX.Element
export function FaRegularFaceSurprise(props: IconProps): JSX.Element
export function FaRegularFaceTired(props: IconProps): JSX.Element
export function FaRegularFileAudio(props: IconProps): JSX.Element
export function FaRegularFileCode(props: IconProps): JSX.Element
export function FaRegularFileExcel(props: IconProps): JSX.Element
export function FaRegularFileImage(props: IconProps): JSX.Element
export function FaRegularFileLines(props: IconProps): JSX.Element
export function FaRegularFilePdf(props: IconProps): JSX.Element
export function FaRegularFilePowerpoint(props: IconProps): JSX.Element
export function FaRegularFileVideo(props: IconProps): JSX.Element
export function FaRegularFileWord(props: IconProps): JSX.Element
export function FaRegularFileZipper(props: IconProps): JSX.Element
export function FaRegularFile(props: IconProps): JSX.Element
export function FaRegularFlag(props: IconProps): JSX.Element
export function FaRegularFloppyDisk(props: IconProps): JSX.Element
export function FaRegularFolderClosed(props: IconProps): JSX.Element
export function FaRegularFolderOpen(props: IconProps): JSX.Element
export function FaRegularFolder(props: IconProps): JSX.Element
export function FaRegularFontAwesome(props: IconProps): JSX.Element
export function FaRegularFutbol(props: IconProps): JSX.Element
export function FaRegularGem(props: IconProps): JSX.Element
export function FaRegularHandBackFist(props: IconProps): JSX.Element
export function FaRegularHandLizard(props: IconProps): JSX.Element
export function FaRegularHandPeace(props: IconProps): JSX.Element
export function FaRegularHandPointDown(props: IconProps): JSX.Element
export function FaRegularHandPointLeft(props: IconProps): JSX.Element
export function FaRegularHandPointRight(props: IconProps): JSX.Element
export function FaRegularHandPointUp(props: IconProps): JSX.Element
export function FaRegularHandPointer(props: IconProps): JSX.Element
export function FaRegularHandScissors(props: IconProps): JSX.Element
export function FaRegularHandSpock(props: IconProps): JSX.Element
export function FaRegularHand(props: IconProps): JSX.Element
export function FaRegularHandshake(props: IconProps): JSX.Element
export function FaRegularHardDrive(props: IconProps): JSX.Element
export function FaRegularHeart(props: IconProps): JSX.Element
export function FaRegularHospital(props: IconProps): JSX.Element
export function FaRegularHourglassHalf(props: IconProps): JSX.Element
export function FaRegularHourglass(props: IconProps): JSX.Element
export function FaRegularIdBadge(props: IconProps): JSX.Element
export function FaRegularIdCard(props: IconProps): JSX.Element
export function FaRegularImage(props: IconProps): JSX.Element
export function FaRegularImages(props: IconProps): JSX.Element
export function FaRegularKeyboard(props: IconProps): JSX.Element
export function FaRegularLemon(props: IconProps): JSX.Element
export function FaRegularLifeRing(props: IconProps): JSX.Element
export function FaRegularLightbulb(props: IconProps): JSX.Element
export function FaRegularMap(props: IconProps): JSX.Element
export function FaRegularMessage(props: IconProps): JSX.Element
export function FaRegularMoneyBill1(props: IconProps): JSX.Element
export function FaRegularMoon(props: IconProps): JSX.Element
export function FaRegularNewspaper(props: IconProps): JSX.Element
export function FaRegularNoteSticky(props: IconProps): JSX.Element
export function FaRegularObjectGroup(props: IconProps): JSX.Element
export function FaRegularObjectUngroup(props: IconProps): JSX.Element
export function FaRegularPaperPlane(props: IconProps): JSX.Element
export function FaRegularPaste(props: IconProps): JSX.Element
export function FaRegularPenToSquare(props: IconProps): JSX.Element
export function FaRegularRectangleList(props: IconProps): JSX.Element
export function FaRegularRectangleXmark(props: IconProps): JSX.Element
export function FaRegularRegistered(props: IconProps): JSX.Element
export function FaRegularShareFromSquare(props: IconProps): JSX.Element
export function FaRegularSnowflake(props: IconProps): JSX.Element
export function FaRegularSquareCaretDown(props: IconProps): JSX.Element
export function FaRegularSquareCaretLeft(props: IconProps): JSX.Element
export function FaRegularSquareCaretRight(props: IconProps): JSX.Element
export function FaRegularSquareCaretUp(props: IconProps): JSX.Element
export function FaRegularSquareCheck(props: IconProps): JSX.Element
export function FaRegularSquareFull(props: IconProps): JSX.Element
export function FaRegularSquareMinus(props: IconProps): JSX.Element
export function FaRegularSquarePlus(props: IconProps): JSX.Element
export function FaRegularSquare(props: IconProps): JSX.Element
export function FaRegularStarHalfStroke(props: IconProps): JSX.Element
export function FaRegularStarHalf(props: IconProps): JSX.Element
export function FaRegularStar(props: IconProps): JSX.Element
export function FaRegularSun(props: IconProps): JSX.Element
export function FaRegularThumbsDown(props: IconProps): JSX.Element
export function FaRegularThumbsUp(props: IconProps): JSX.Element
export function FaRegularTrashCan(props: IconProps): JSX.Element
export function FaRegularUser(props: IconProps): JSX.Element
export function FaRegularWindowMaximize(props: IconProps): JSX.Element
export function FaRegularWindowMinimize(props: IconProps): JSX.Element
export function FaRegularWindowRestore(props: IconProps): JSX.Element
