// AUTO-GENERATED FILE. DO NOT EDIT BY HAND.
// Icon set: antdesign/twotone | License: MIT (MIT_URL)
import type { JSX } from 'solid-js'
import type { IconProps } from '..//types'

export function AntdTwotoneAccountBook(props: IconProps): JSX.Element
export function AntdTwotoneAlert(props: IconProps): JSX.Element
export function AntdTwotoneApi(props: IconProps): JSX.Element
export function AntdTwotoneAppstore(props: IconProps): JSX.Element
export function AntdTwotoneAudio(props: IconProps): JSX.Element
export function AntdTwotoneBank(props: IconProps): JSX.Element
export function AntdTwotoneBell(props: IconProps): JSX.Element
export function AntdTwotoneBook(props: IconProps): JSX.Element
export function AntdTwotoneBoxPlot(props: IconProps): JSX.Element
export function AntdTwotoneBug(props: IconProps): JSX.Element
export function AntdTwotoneBuild(props: IconProps): JSX.Element
export function AntdTwotoneBulb(props: IconProps): JSX.Element
export function AntdTwotoneCalculator(props: IconProps): JSX.Element
export function AntdTwotoneCalendar(props: IconProps): JSX.Element
export function AntdTwotoneCamera(props: IconProps): JSX.Element
export function AntdTwotoneCar(props: IconProps): JSX.Element
export function AntdTwotoneCarryOut(props: IconProps): JSX.Element
export function AntdTwotoneCheckCircle(props: IconProps): JSX.Element
export function AntdTwotoneCheckSquare(props: IconProps): JSX.Element
export function AntdTwotoneCiCircle(props: IconProps): JSX.Element
export function AntdTwotoneCi(props: IconProps): JSX.Element
export function AntdTwotoneClockCircle(props: IconProps): JSX.Element
export function AntdTwotoneCloseCircle(props: IconProps): JSX.Element
export function AntdTwotoneCloseSquare(props: IconProps): JSX.Element
export function AntdTwotoneCloud(props: IconProps): JSX.Element
export function AntdTwotoneCode(props: IconProps): JSX.Element
export function AntdTwotoneCompass(props: IconProps): JSX.Element
export function AntdTwotoneContacts(props: IconProps): JSX.Element
export function AntdTwotoneContainer(props: IconProps): JSX.Element
export function AntdTwotoneControl(props: IconProps): JSX.Element
export function AntdTwotoneCopy(props: IconProps): JSX.Element
export function AntdTwotoneCopyrightCircle(props: IconProps): JSX.Element
export function AntdTwotoneCopyright(props: IconProps): JSX.Element
export function AntdTwotoneCreditCard(props: IconProps): JSX.Element
export function AntdTwotoneCrown(props: IconProps): JSX.Element
export function AntdTwotoneCustomerService(props: IconProps): JSX.Element
export function AntdTwotoneDashboard(props: IconProps): JSX.Element
export function AntdTwotoneDatabase(props: IconProps): JSX.Element
export function AntdTwotoneDelete(props: IconProps): JSX.Element
export function AntdTwotoneDiff(props: IconProps): JSX.Element
export function AntdTwotoneDislike(props: IconProps): JSX.Element
export function AntdTwotoneDollarCircle(props: IconProps): JSX.Element
export function AntdTwotoneDollar(props: IconProps): JSX.Element
export function AntdTwotoneDownCircle(props: IconProps): JSX.Element
export function AntdTwotoneDownSquare(props: IconProps): JSX.Element
export function AntdTwotoneEdit(props: IconProps): JSX.Element
export function AntdTwotoneEnvironment(props: IconProps): JSX.Element
export function AntdTwotoneEuroCircle(props: IconProps): JSX.Element
export function AntdTwotoneEuro(props: IconProps): JSX.Element
export function AntdTwotoneExclamationCircle(props: IconProps): JSX.Element
export function AntdTwotoneExperiment(props: IconProps): JSX.Element
export function AntdTwotoneEyeInvisible(props: IconProps): JSX.Element
export function AntdTwotoneEye(props: IconProps): JSX.Element
export function AntdTwotoneFileAdd(props: IconProps): JSX.Element
export function AntdTwotoneFileExcel(props: IconProps): JSX.Element
export function AntdTwotoneFileExclamation(props: IconProps): JSX.Element
export function AntdTwotoneFileImage(props: IconProps): JSX.Element
export function AntdTwotoneFileMarkdown(props: IconProps): JSX.Element
export function AntdTwotoneFilePdf(props: IconProps): JSX.Element
export function AntdTwotoneFilePpt(props: IconProps): JSX.Element
export function AntdTwotoneFileText(props: IconProps): JSX.Element
export function AntdTwotoneFileUnknown(props: IconProps): JSX.Element
export function AntdTwotoneFileWord(props: IconProps): JSX.Element
export function AntdTwotoneFileZip(props: IconProps): JSX.Element
export function AntdTwotoneFile(props: IconProps): JSX.Element
export function AntdTwotoneFilter(props: IconProps): JSX.Element
export function AntdTwotoneFire(props: IconProps): JSX.Element
export function AntdTwotoneFlag(props: IconProps): JSX.Element
export function AntdTwotoneFolderAdd(props: IconProps): JSX.Element
export function AntdTwotoneFolderOpen(props: IconProps): JSX.Element
export function AntdTwotoneFolder(props: IconProps): JSX.Element
export function AntdTwotoneFrown(props: IconProps): JSX.Element
export function AntdTwotoneFund(props: IconProps): JSX.Element
export function AntdTwotoneFunnelPlot(props: IconProps): JSX.Element
export function AntdTwotoneGift(props: IconProps): JSX.Element
export function AntdTwotoneGold(props: IconProps): JSX.Element
export function AntdTwotoneHdd(props: IconProps): JSX.Element
export function AntdTwotoneHeart(props: IconProps): JSX.Element
export function AntdTwotoneHighlight(props: IconProps): JSX.Element
export function AntdTwotoneHome(props: IconProps): JSX.Element
export function AntdTwotoneHourglass(props: IconProps): JSX.Element
export function AntdTwotoneHtml5(props: IconProps): JSX.Element
export function AntdTwotoneIdcard(props: IconProps): JSX.Element
export function AntdTwotoneInfoCircle(props: IconProps): JSX.Element
export function AntdTwotoneInsurance(props: IconProps): JSX.Element
export function AntdTwotoneInteraction(props: IconProps): JSX.Element
export function AntdTwotoneLayout(props: IconProps): JSX.Element
export function AntdTwotoneLeftCircle(props: IconProps): JSX.Element
export function AntdTwotoneLeftSquare(props: IconProps): JSX.Element
export function AntdTwotoneLike(props: IconProps): JSX.Element
export function AntdTwotoneLock(props: IconProps): JSX.Element
export function AntdTwotoneMail(props: IconProps): JSX.Element
export function AntdTwotoneMedicineBox(props: IconProps): JSX.Element
export function AntdTwotoneMeh(props: IconProps): JSX.Element
export function AntdTwotoneMessage(props: IconProps): JSX.Element
export function AntdTwotoneMinusCircle(props: IconProps): JSX.Element
export function AntdTwotoneMinusSquare(props: IconProps): JSX.Element
export function AntdTwotoneMobile(props: IconProps): JSX.Element
export function AntdTwotoneMoneyCollect(props: IconProps): JSX.Element
export function AntdTwotoneNotification(props: IconProps): JSX.Element
export function AntdTwotonePauseCircle(props: IconProps): JSX.Element
export function AntdTwotonePhone(props: IconProps): JSX.Element
export function AntdTwotonePicture(props: IconProps): JSX.Element
export function AntdTwotonePieChart(props: IconProps): JSX.Element
export function AntdTwotonePlayCircle(props: IconProps): JSX.Element
export function AntdTwotonePlaySquare(props: IconProps): JSX.Element
export function AntdTwotonePlusCircle(props: IconProps): JSX.Element
export function AntdTwotonePlusSquare(props: IconProps): JSX.Element
export function AntdTwotonePoundCircle(props: IconProps): JSX.Element
export function AntdTwotonePrinter(props: IconProps): JSX.Element
export function AntdTwotoneProfile(props: IconProps): JSX.Element
export function AntdTwotoneProject(props: IconProps): JSX.Element
export function AntdTwotonePropertySafety(props: IconProps): JSX.Element
export function AntdTwotonePushpin(props: IconProps): JSX.Element
export function AntdTwotoneQuestionCircle(props: IconProps): JSX.Element
export function AntdTwotoneReconciliation(props: IconProps): JSX.Element
export function AntdTwotoneRedEnvelope(props: IconProps): JSX.Element
export function AntdTwotoneRest(props: IconProps): JSX.Element
export function AntdTwotoneRightCircle(props: IconProps): JSX.Element
export function AntdTwotoneRightSquare(props: IconProps): JSX.Element
export function AntdTwotoneRocket(props: IconProps): JSX.Element
export function AntdTwotoneSafetyCertificate(props: IconProps): JSX.Element
export function AntdTwotoneSave(props: IconProps): JSX.Element
export function AntdTwotoneSchedule(props: IconProps): JSX.Element
export function AntdTwotoneSecurityScan(props: IconProps): JSX.Element
export function AntdTwotoneSetting(props: IconProps): JSX.Element
export function AntdTwotoneShop(props: IconProps): JSX.Element
export function AntdTwotoneShopping(props: IconProps): JSX.Element
export function AntdTwotoneSkin(props: IconProps): JSX.Element
export function AntdTwotoneSliders(props: IconProps): JSX.Element
export function AntdTwotoneSmile(props: IconProps): JSX.Element
export function AntdTwotoneSnippets(props: IconProps): JSX.Element
export function AntdTwotoneSound(props: IconProps): JSX.Element
export function AntdTwotoneStar(props: IconProps): JSX.Element
export function AntdTwotoneStop(props: IconProps): JSX.Element
export function AntdTwotoneSwitcher(props: IconProps): JSX.Element
export function AntdTwotoneTablet(props: IconProps): JSX.Element
export function AntdTwotoneTag(props: IconProps): JSX.Element
export function AntdTwotoneTags(props: IconProps): JSX.Element
export function AntdTwotoneThunderbolt(props: IconProps): JSX.Element
export function AntdTwotoneTool(props: IconProps): JSX.Element
export function AntdTwotoneTrademarkCircle(props: IconProps): JSX.Element
export function AntdTwotoneTrophy(props: IconProps): JSX.Element
export function AntdTwotoneUnlock(props: IconProps): JSX.Element
export function AntdTwotoneUpCircle(props: IconProps): JSX.Element
export function AntdTwotoneUpSquare(props: IconProps): JSX.Element
export function AntdTwotoneUsb(props: IconProps): JSX.Element
export function AntdTwotoneVideoCamera(props: IconProps): JSX.Element
export function AntdTwotoneWallet(props: IconProps): JSX.Element
export function AntdTwotoneWarning(props: IconProps): JSX.Element
