// AUTO-GENERATED FILE. DO NOT EDIT BY HAND.
// Icon set: boxicons | License: MIT (MIT_URL)
import type { JSX } from 'solid-js'
import type { IconProps } from './/types'

export function BoxBxAbacus(props: IconProps): JSX.Element
export function BoxBxAccessibility(props: IconProps): JSX.Element
export function BoxBxAddToQueue(props: IconProps): JSX.Element
export function BoxBxAdjust(props: IconProps): JSX.Element
export function BoxBxAlarmAdd(props: IconProps): JSX.Element
export function BoxBxAlarmExclamation(props: IconProps): JSX.Element
export function BoxBxAlarmOff(props: IconProps): JSX.Element
export function BoxBxAlarmSnooze(props: IconProps): JSX.Element
export function BoxBxAlarm(props: IconProps): JSX.Element
export function BoxBxAlbum(props: IconProps): JSX.Element
export function BoxBxAlignJustify(props: IconProps): JSX.Element
export function BoxBxAlignLeft(props: IconProps): JSX.Element
export function BoxBxAlignMiddle(props: IconProps): JSX.Element
export function BoxBxAlignRight(props: IconProps): JSX.Element
export function BoxBxAnalyse(props: IconProps): JSX.Element
export function BoxBxAnchor(props: IconProps): JSX.Element
export function BoxBxAngry(props: IconProps): JSX.Element
export function BoxBxAperture(props: IconProps): JSX.Element
export function BoxBxArch(props: IconProps): JSX.Element
export function BoxBxArchiveIn(props: IconProps): JSX.Element
export function BoxBxArchiveOut(props: IconProps): JSX.Element
export function BoxBxArchive(props: IconProps): JSX.Element
export function BoxBxArea(props: IconProps): JSX.Element
export function BoxBxArrowBack(props: IconProps): JSX.Element
export function BoxBxArrowFromBottom(props: IconProps): JSX.Element
export function BoxBxArrowFromLeft(props: IconProps): JSX.Element
export function BoxBxArrowFromRight(props: IconProps): JSX.Element
export function BoxBxArrowFromTop(props: IconProps): JSX.Element
export function BoxBxArrowToBottom(props: IconProps): JSX.Element
export function BoxBxArrowToLeft(props: IconProps): JSX.Element
export function BoxBxArrowToRight(props: IconProps): JSX.Element
export function BoxBxArrowToTop(props: IconProps): JSX.Element
export function BoxBxAt(props: IconProps): JSX.Element
export function BoxBxAtom(props: IconProps): JSX.Element
export function BoxBxAward(props: IconProps): JSX.Element
export function BoxBxBadgeCheck(props: IconProps): JSX.Element
export function BoxBxBadge(props: IconProps): JSX.Element
export function BoxBxBaguette(props: IconProps): JSX.Element
export function BoxBxBall(props: IconProps): JSX.Element
export function BoxBxBandAid(props: IconProps): JSX.Element
export function BoxBxBarChartAlt2(props: IconProps): JSX.Element
export function BoxBxBarChartAlt(props: IconProps): JSX.Element
export function BoxBxBarChartSquare(props: IconProps): JSX.Element
export function BoxBxBarChart(props: IconProps): JSX.Element
export function BoxBxBarcodeReader(props: IconProps): JSX.Element
export function BoxBxBarcode(props: IconProps): JSX.Element
export function BoxBxBaseball(props: IconProps): JSX.Element
export function BoxBxBasket(props: IconProps): JSX.Element
export function BoxBxBasketball(props: IconProps): JSX.Element
export function BoxBxBath(props: IconProps): JSX.Element
export function BoxBxBattery(props: IconProps): JSX.Element
export function BoxBxBed(props: IconProps): JSX.Element
export function BoxBxBeenHere(props: IconProps): JSX.Element
export function BoxBxBeer(props: IconProps): JSX.Element
export function BoxBxBellMinus(props: IconProps): JSX.Element
export function BoxBxBellOff(props: IconProps): JSX.Element
export function BoxBxBellPlus(props: IconProps): JSX.Element
export function BoxBxBell(props: IconProps): JSX.Element
export function BoxBxBible(props: IconProps): JSX.Element
export function BoxBxBitcoin(props: IconProps): JSX.Element
export function BoxBxBlanket(props: IconProps): JSX.Element
export function BoxBxBlock(props: IconProps): JSX.Element
export function BoxBxBluetooth(props: IconProps): JSX.Element
export function BoxBxBody(props: IconProps): JSX.Element
export function BoxBxBold(props: IconProps): JSX.Element
export function BoxBxBoltCircle(props: IconProps): JSX.Element
export function BoxBxBomb(props: IconProps): JSX.Element
export function BoxBxBone(props: IconProps): JSX.Element
export function BoxBxBong(props: IconProps): JSX.Element
export function BoxBxBookAdd(props: IconProps): JSX.Element
export function BoxBxBookAlt(props: IconProps): JSX.Element
export function BoxBxBookBookmark(props: IconProps): JSX.Element
export function BoxBxBookContent(props: IconProps): JSX.Element
export function BoxBxBookHeart(props: IconProps): JSX.Element
export function BoxBxBookOpen(props: IconProps): JSX.Element
export function BoxBxBookReader(props: IconProps): JSX.Element
export function BoxBxBook(props: IconProps): JSX.Element
export function BoxBxBookmarkAltMinus(props: IconProps): JSX.Element
export function BoxBxBookmarkAltPlus(props: IconProps): JSX.Element
export function BoxBxBookmarkAlt(props: IconProps): JSX.Element
export function BoxBxBookmarkHeart(props: IconProps): JSX.Element
export function BoxBxBookmarkMinus(props: IconProps): JSX.Element
export function BoxBxBookmarkPlus(props: IconProps): JSX.Element
export function BoxBxBookmark(props: IconProps): JSX.Element
export function BoxBxBookmarks(props: IconProps): JSX.Element
export function BoxBxBorderAll(props: IconProps): JSX.Element
export function BoxBxBorderBottom(props: IconProps): JSX.Element
export function BoxBxBorderInner(props: IconProps): JSX.Element
export function BoxBxBorderLeft(props: IconProps): JSX.Element
export function BoxBxBorderNone(props: IconProps): JSX.Element
export function BoxBxBorderOuter(props: IconProps): JSX.Element
export function BoxBxBorderRadius(props: IconProps): JSX.Element
export function BoxBxBorderRight(props: IconProps): JSX.Element
export function BoxBxBorderTop(props: IconProps): JSX.Element
export function BoxBxBot(props: IconProps): JSX.Element
export function BoxBxBowlHot(props: IconProps): JSX.Element
export function BoxBxBowlRice(props: IconProps): JSX.Element
export function BoxBxBowlingBall(props: IconProps): JSX.Element
export function BoxBxBox(props: IconProps): JSX.Element
export function BoxBxBracket(props: IconProps): JSX.Element
export function BoxBxBraille(props: IconProps): JSX.Element
export function BoxBxBrain(props: IconProps): JSX.Element
export function BoxBxBriefcaseAlt2(props: IconProps): JSX.Element
export function BoxBxBriefcaseAlt(props: IconProps): JSX.Element
export function BoxBxBriefcase(props: IconProps): JSX.Element
export function BoxBxBrightnessHalf(props: IconProps): JSX.Element
export function BoxBxBrightness(props: IconProps): JSX.Element
export function BoxBxBroadcast(props: IconProps): JSX.Element
export function BoxBxBrushAlt(props: IconProps): JSX.Element
export function BoxBxBrush(props: IconProps): JSX.Element
export function BoxBxBugAlt(props: IconProps): JSX.Element
export function BoxBxBug(props: IconProps): JSX.Element
export function BoxBxBuildingHouse(props: IconProps): JSX.Element
export function BoxBxBuilding(props: IconProps): JSX.Element
export function BoxBxBuildings(props: IconProps): JSX.Element
export function BoxBxBulb(props: IconProps): JSX.Element
export function BoxBxBullseye(props: IconProps): JSX.Element
export function BoxBxBuoy(props: IconProps): JSX.Element
export function BoxBxBusSchool(props: IconProps): JSX.Element
export function BoxBxBus(props: IconProps): JSX.Element
export function BoxBxCabinet(props: IconProps): JSX.Element
export function BoxBxCableCar(props: IconProps): JSX.Element
export function BoxBxCake(props: IconProps): JSX.Element
export function BoxBxCalculator(props: IconProps): JSX.Element
export function BoxBxCalendarAlt(props: IconProps): JSX.Element
export function BoxBxCalendarCheck(props: IconProps): JSX.Element
export function BoxBxCalendarEdit(props: IconProps): JSX.Element
export function BoxBxCalendarEvent(props: IconProps): JSX.Element
export function BoxBxCalendarExclamation(props: IconProps): JSX.Element
export function BoxBxCalendarHeart(props: IconProps): JSX.Element
export function BoxBxCalendarMinus(props: IconProps): JSX.Element
export function BoxBxCalendarPlus(props: IconProps): JSX.Element
export function BoxBxCalendarStar(props: IconProps): JSX.Element
export function BoxBxCalendarWeek(props: IconProps): JSX.Element
export function BoxBxCalendarX(props: IconProps): JSX.Element
export function BoxBxCalendar(props: IconProps): JSX.Element
export function BoxBxCameraHome(props: IconProps): JSX.Element
export function BoxBxCameraMovie(props: IconProps): JSX.Element
export function BoxBxCameraOff(props: IconProps): JSX.Element
export function BoxBxCamera(props: IconProps): JSX.Element
export function BoxBxCandles(props: IconProps): JSX.Element
export function BoxBxCapsule(props: IconProps): JSX.Element
export function BoxBxCaptions(props: IconProps): JSX.Element
export function BoxBxCar(props: IconProps): JSX.Element
export function BoxBxCard(props: IconProps): JSX.Element
export function BoxBxCaretDownCircle(props: IconProps): JSX.Element
export function BoxBxCaretDownSquare(props: IconProps): JSX.Element
export function BoxBxCaretDown(props: IconProps): JSX.Element
export function BoxBxCaretLeftCircle(props: IconProps): JSX.Element
export function BoxBxCaretLeftSquare(props: IconProps): JSX.Element
export function BoxBxCaretLeft(props: IconProps): JSX.Element
export function BoxBxCaretRightCircle(props: IconProps): JSX.Element
export function BoxBxCaretRightSquare(props: IconProps): JSX.Element
export function BoxBxCaretRight(props: IconProps): JSX.Element
export function BoxBxCaretUpCircle(props: IconProps): JSX.Element
export function BoxBxCaretUpSquare(props: IconProps): JSX.Element
export function BoxBxCaretUp(props: IconProps): JSX.Element
export function BoxBxCarousel(props: IconProps): JSX.Element
export function BoxBxCartAdd(props: IconProps): JSX.Element
export function BoxBxCartAlt(props: IconProps): JSX.Element
export function BoxBxCartDownload(props: IconProps): JSX.Element
export function BoxBxCart(props: IconProps): JSX.Element
export function BoxBxCast(props: IconProps): JSX.Element
export function BoxBxCategoryAlt(props: IconProps): JSX.Element
export function BoxBxCategory(props: IconProps): JSX.Element
export function BoxBxCctv(props: IconProps): JSX.Element
export function BoxBxCertification(props: IconProps): JSX.Element
export function BoxBxChair(props: IconProps): JSX.Element
export function BoxBxChalkboard(props: IconProps): JSX.Element
export function BoxBxChart(props: IconProps): JSX.Element
export function BoxBxChat(props: IconProps): JSX.Element
export function BoxBxCheckCircle(props: IconProps): JSX.Element
export function BoxBxCheckDouble(props: IconProps): JSX.Element
export function BoxBxCheckShield(props: IconProps): JSX.Element
export function BoxBxCheckSquare(props: IconProps): JSX.Element
export function BoxBxCheck(props: IconProps): JSX.Element
export function BoxBxCheckboxChecked(props: IconProps): JSX.Element
export function BoxBxCheckboxMinus(props: IconProps): JSX.Element
export function BoxBxCheckboxSquare(props: IconProps): JSX.Element
export function BoxBxCheckbox(props: IconProps): JSX.Element
export function BoxBxCheese(props: IconProps): JSX.Element
export function BoxBxChevronDownCircle(props: IconProps): JSX.Element
export function BoxBxChevronDownSquare(props: IconProps): JSX.Element
export function BoxBxChevronDown(props: IconProps): JSX.Element
export function BoxBxChevronLeftCircle(props: IconProps): JSX.Element
export function BoxBxChevronLeftSquare(props: IconProps): JSX.Element
export function BoxBxChevronLeft(props: IconProps): JSX.Element
export function BoxBxChevronRightCircle(props: IconProps): JSX.Element
export function BoxBxChevronRightSquare(props: IconProps): JSX.Element
export function BoxBxChevronRight(props: IconProps): JSX.Element
export function BoxBxChevronUpCircle(props: IconProps): JSX.Element
export function BoxBxChevronUpSquare(props: IconProps): JSX.Element
export function BoxBxChevronUp(props: IconProps): JSX.Element
export function BoxBxChevronsDown(props: IconProps): JSX.Element
export function BoxBxChevronsLeft(props: IconProps): JSX.Element
export function BoxBxChevronsRight(props: IconProps): JSX.Element
export function BoxBxChevronsUp(props: IconProps): JSX.Element
export function BoxBxChild(props: IconProps): JSX.Element
export function BoxBxChip(props: IconProps): JSX.Element
export function BoxBxChurch(props: IconProps): JSX.Element
export function BoxBxCircleHalf(props: IconProps): JSX.Element
export function BoxBxCircleQuarter(props: IconProps): JSX.Element
export function BoxBxCircleThreeQuarter(props: IconProps): JSX.Element
export function BoxBxCircle(props: IconProps): JSX.Element
export function BoxBxClinic(props: IconProps): JSX.Element
export function BoxBxClipboard(props: IconProps): JSX.Element
export function BoxBxCloset(props: IconProps): JSX.Element
export function BoxBxCloudDownload(props: IconProps): JSX.Element
export function BoxBxCloudDrizzle(props: IconProps): JSX.Element
export function BoxBxCloudLightRain(props: IconProps): JSX.Element
export function BoxBxCloudLightning(props: IconProps): JSX.Element
export function BoxBxCloudRain(props: IconProps): JSX.Element
export function BoxBxCloudSnow(props: IconProps): JSX.Element
export function BoxBxCloudUpload(props: IconProps): JSX.Element
export function BoxBxCloud(props: IconProps): JSX.Element
export function BoxBxCodeAlt(props: IconProps): JSX.Element
export function BoxBxCodeBlock(props: IconProps): JSX.Element
export function BoxBxCodeCurly(props: IconProps): JSX.Element
export function BoxBxCode(props: IconProps): JSX.Element
export function BoxBxCoffeeTogo(props: IconProps): JSX.Element
export function BoxBxCoffee(props: IconProps): JSX.Element
export function BoxBxCog(props: IconProps): JSX.Element
export function BoxBxCoinStack(props: IconProps): JSX.Element
export function BoxBxCoin(props: IconProps): JSX.Element
export function BoxBxCollapseAlt(props: IconProps): JSX.Element
export function BoxBxCollapseHorizontal(props: IconProps): JSX.Element
export function BoxBxCollapseVertical(props: IconProps): JSX.Element
export function BoxBxCollapse(props: IconProps): JSX.Element
export function BoxBxCollection(props: IconProps): JSX.Element
export function BoxBxColorFill(props: IconProps): JSX.Element
export function BoxBxColor(props: IconProps): JSX.Element
export function BoxBxColumns(props: IconProps): JSX.Element
export function BoxBxCommand(props: IconProps): JSX.Element
export function BoxBxCommentAdd(props: IconProps): JSX.Element
export function BoxBxCommentCheck(props: IconProps): JSX.Element
export function BoxBxCommentDetail(props: IconProps): JSX.Element
export function BoxBxCommentDots(props: IconProps): JSX.Element
export function BoxBxCommentEdit(props: IconProps): JSX.Element
export function BoxBxCommentError(props: IconProps): JSX.Element
export function BoxBxCommentMinus(props: IconProps): JSX.Element
export function BoxBxCommentX(props: IconProps): JSX.Element
export function BoxBxComment(props: IconProps): JSX.Element
export function BoxBxCompass(props: IconProps): JSX.Element
export function BoxBxConfused(props: IconProps): JSX.Element
export function BoxBxConversation(props: IconProps): JSX.Element
export function BoxBxCookie(props: IconProps): JSX.Element
export function BoxBxCool(props: IconProps): JSX.Element
export function BoxBxCopyAlt(props: IconProps): JSX.Element
export function BoxBxCopy(props: IconProps): JSX.Element
export function BoxBxCopyright(props: IconProps): JSX.Element
export function BoxBxCreditCardAlt(props: IconProps): JSX.Element
export function BoxBxCreditCardFront(props: IconProps): JSX.Element
export function BoxBxCreditCard(props: IconProps): JSX.Element
export function BoxBxCricketBall(props: IconProps): JSX.Element
export function BoxBxCrop(props: IconProps): JSX.Element
export function BoxBxCross(props: IconProps): JSX.Element
export function BoxBxCrosshair(props: IconProps): JSX.Element
export function BoxBxCrown(props: IconProps): JSX.Element
export function BoxBxCubeAlt(props: IconProps): JSX.Element
export function BoxBxCube(props: IconProps): JSX.Element
export function BoxBxCuboid(props: IconProps): JSX.Element
export function BoxBxCurrentLocation(props: IconProps): JSX.Element
export function BoxBxCustomize(props: IconProps): JSX.Element
export function BoxBxCut(props: IconProps): JSX.Element
export function BoxBxCycling(props: IconProps): JSX.Element
export function BoxBxCylinder(props: IconProps): JSX.Element
export function BoxBxData(props: IconProps): JSX.Element
export function BoxBxDesktop(props: IconProps): JSX.Element
export function BoxBxDetail(props: IconProps): JSX.Element
export function BoxBxDevices(props: IconProps): JSX.Element
export function BoxBxDialpadAlt(props: IconProps): JSX.Element
export function BoxBxDialpad(props: IconProps): JSX.Element
export function BoxBxDiamond(props: IconProps): JSX.Element
export function BoxBxDice1(props: IconProps): JSX.Element
export function BoxBxDice2(props: IconProps): JSX.Element
export function BoxBxDice3(props: IconProps): JSX.Element
export function BoxBxDice4(props: IconProps): JSX.Element
export function BoxBxDice5(props: IconProps): JSX.Element
export function BoxBxDice6(props: IconProps): JSX.Element
export function BoxBxDirections(props: IconProps): JSX.Element
export function BoxBxDisc(props: IconProps): JSX.Element
export function BoxBxDish(props: IconProps): JSX.Element
export function BoxBxDislike(props: IconProps): JSX.Element
export function BoxBxDizzy(props: IconProps): JSX.Element
export function BoxBxDna(props: IconProps): JSX.Element
export function BoxBxDockBottom(props: IconProps): JSX.Element
export function BoxBxDockLeft(props: IconProps): JSX.Element
export function BoxBxDockRight(props: IconProps): JSX.Element
export function BoxBxDockTop(props: IconProps): JSX.Element
export function BoxBxDollarCircle(props: IconProps): JSX.Element
export function BoxBxDollar(props: IconProps): JSX.Element
export function BoxBxDonateBlood(props: IconProps): JSX.Element
export function BoxBxDonateHeart(props: IconProps): JSX.Element
export function BoxBxDoorOpen(props: IconProps): JSX.Element
export function BoxBxDotsHorizontalRounded(props: IconProps): JSX.Element
export function BoxBxDotsHorizontal(props: IconProps): JSX.Element
export function BoxBxDotsVerticalRounded(props: IconProps): JSX.Element
export function BoxBxDotsVertical(props: IconProps): JSX.Element
export function BoxBxDoughnutChart(props: IconProps): JSX.Element
export function BoxBxDownArrowAlt(props: IconProps): JSX.Element
export function BoxBxDownArrowCircle(props: IconProps): JSX.Element
export function BoxBxDownArrow(props: IconProps): JSX.Element
export function BoxBxDownload(props: IconProps): JSX.Element
export function BoxBxDownvote(props: IconProps): JSX.Element
export function BoxBxDrink(props: IconProps): JSX.Element
export function BoxBxDroplet(props: IconProps): JSX.Element
export function BoxBxDumbbell(props: IconProps): JSX.Element
export function BoxBxDuplicate(props: IconProps): JSX.Element
export function BoxBxEditAlt(props: IconProps): JSX.Element
export function BoxBxEdit(props: IconProps): JSX.Element
export function BoxBxEnvelopeOpen(props: IconProps): JSX.Element
export function BoxBxEnvelope(props: IconProps): JSX.Element
export function BoxBxEqualizer(props: IconProps): JSX.Element
export function BoxBxEraser(props: IconProps): JSX.Element
export function BoxBxErrorAlt(props: IconProps): JSX.Element
export function BoxBxErrorCircle(props: IconProps): JSX.Element
export function BoxBxError(props: IconProps): JSX.Element
export function BoxBxEuro(props: IconProps): JSX.Element
export function BoxBxExclude(props: IconProps): JSX.Element
export function BoxBxExitFullscreen(props: IconProps): JSX.Element
export function BoxBxExit(props: IconProps): JSX.Element
export function BoxBxExpandAlt(props: IconProps): JSX.Element
export function BoxBxExpandHorizontal(props: IconProps): JSX.Element
export function BoxBxExpandVertical(props: IconProps): JSX.Element
export function BoxBxExpand(props: IconProps): JSX.Element
export function BoxBxExport(props: IconProps): JSX.Element
export function BoxBxExtension(props: IconProps): JSX.Element
export function BoxBxFace(props: IconProps): JSX.Element
export function BoxBxFastForwardCircle(props: IconProps): JSX.Element
export function BoxBxFastForward(props: IconProps): JSX.Element
export function BoxBxFemaleSign(props: IconProps): JSX.Element
export function BoxBxFemale(props: IconProps): JSX.Element
export function BoxBxFileBlank(props: IconProps): JSX.Element
export function BoxBxFileFind(props: IconProps): JSX.Element
export function BoxBxFile(props: IconProps): JSX.Element
export function BoxBxFilm(props: IconProps): JSX.Element
export function BoxBxFilterAlt(props: IconProps): JSX.Element
export function BoxBxFilter(props: IconProps): JSX.Element
export function BoxBxFingerprint(props: IconProps): JSX.Element
export function BoxBxFirstAid(props: IconProps): JSX.Element
export function BoxBxFirstPage(props: IconProps): JSX.Element
export function BoxBxFlag(props: IconProps): JSX.Element
export function BoxBxFolderMinus(props: IconProps): JSX.Element
export function BoxBxFolderOpen(props: IconProps): JSX.Element
export function BoxBxFolderPlus(props: IconProps): JSX.Element
export function BoxBxFolder(props: IconProps): JSX.Element
export function BoxBxFontColor(props: IconProps): JSX.Element
export function BoxBxFontFamily(props: IconProps): JSX.Element
export function BoxBxFontSize(props: IconProps): JSX.Element
export function BoxBxFont(props: IconProps): JSX.Element
export function BoxBxFoodMenu(props: IconProps): JSX.Element
export function BoxBxFoodTag(props: IconProps): JSX.Element
export function BoxBxFootball(props: IconProps): JSX.Element
export function BoxBxFork(props: IconProps): JSX.Element
export function BoxBxFridge(props: IconProps): JSX.Element
export function BoxBxFullscreen(props: IconProps): JSX.Element
export function BoxBxGame(props: IconProps): JSX.Element
export function BoxBxGasPump(props: IconProps): JSX.Element
export function BoxBxGhost(props: IconProps): JSX.Element
export function BoxBxGift(props: IconProps): JSX.Element
export function BoxBxGitBranch(props: IconProps): JSX.Element
export function BoxBxGitCommit(props: IconProps): JSX.Element
export function BoxBxGitCompare(props: IconProps): JSX.Element
export function BoxBxGitMerge(props: IconProps): JSX.Element
export function BoxBxGitPullRequest(props: IconProps): JSX.Element
export function BoxBxGitRepoForked(props: IconProps): JSX.Element
export function BoxBxGlassesAlt(props: IconProps): JSX.Element
export function BoxBxGlasses(props: IconProps): JSX.Element
export function BoxBxGlobeAlt(props: IconProps): JSX.Element
export function BoxBxGlobe(props: IconProps): JSX.Element
export function BoxBxGridAlt(props: IconProps): JSX.Element
export function BoxBxGridHorizontal(props: IconProps): JSX.Element
export function BoxBxGridSmall(props: IconProps): JSX.Element
export function BoxBxGridVertical(props: IconProps): JSX.Element
export function BoxBxGrid(props: IconProps): JSX.Element
export function BoxBxGroup(props: IconProps): JSX.Element
export function BoxBxHandicap(props: IconProps): JSX.Element
export function BoxBxHappyAlt(props: IconProps): JSX.Element
export function BoxBxHappyBeaming(props: IconProps): JSX.Element
export function BoxBxHappyHeartEyes(props: IconProps): JSX.Element
export function BoxBxHappy(props: IconProps): JSX.Element
export function BoxBxHardHat(props: IconProps): JSX.Element
export function BoxBxHash(props: IconProps): JSX.Element
export function BoxBxHdd(props: IconProps): JSX.Element
export function BoxBxHeading(props: IconProps): JSX.Element
export function BoxBxHeadphone(props: IconProps): JSX.Element
export function BoxBxHealth(props: IconProps): JSX.Element
export function BoxBxHeartCircle(props: IconProps): JSX.Element
export function BoxBxHeartSquare(props: IconProps): JSX.Element
export function BoxBxHeart(props: IconProps): JSX.Element
export function BoxBxHelpCircle(props: IconProps): JSX.Element
export function BoxBxHide(props: IconProps): JSX.Element
export function BoxBxHighlight(props: IconProps): JSX.Element
export function BoxBxHistory(props: IconProps): JSX.Element
export function BoxBxHive(props: IconProps): JSX.Element
export function BoxBxHomeAlt2(props: IconProps): JSX.Element
export function BoxBxHomeAlt(props: IconProps): JSX.Element
export function BoxBxHomeCircle(props: IconProps): JSX.Element
export function BoxBxHomeHeart(props: IconProps): JSX.Element
export function BoxBxHomeSmile(props: IconProps): JSX.Element
export function BoxBxHome(props: IconProps): JSX.Element
export function BoxBxHorizontalCenter(props: IconProps): JSX.Element
export function BoxBxHorizontalLeft(props: IconProps): JSX.Element
export function BoxBxHorizontalRight(props: IconProps): JSX.Element
export function BoxBxHotel(props: IconProps): JSX.Element
export function BoxBxHourglass(props: IconProps): JSX.Element
export function BoxBxIdCard(props: IconProps): JSX.Element
export function BoxBxImageAdd(props: IconProps): JSX.Element
export function BoxBxImageAlt(props: IconProps): JSX.Element
export function BoxBxImage(props: IconProps): JSX.Element
export function BoxBxImages(props: IconProps): JSX.Element
export function BoxBxImport(props: IconProps): JSX.Element
export function BoxBxInfinite(props: IconProps): JSX.Element
export function BoxBxInfoCircle(props: IconProps): JSX.Element
export function BoxBxInfoSquare(props: IconProps): JSX.Element
export function BoxBxInjection(props: IconProps): JSX.Element
export function BoxBxIntersect(props: IconProps): JSX.Element
export function BoxBxItalic(props: IconProps): JSX.Element
export function BoxBxJoystickAlt(props: IconProps): JSX.Element
export function BoxBxJoystickButton(props: IconProps): JSX.Element
export function BoxBxJoystick(props: IconProps): JSX.Element
export function BoxBxKey(props: IconProps): JSX.Element
export function BoxBxKnife(props: IconProps): JSX.Element
export function BoxBxLabel(props: IconProps): JSX.Element
export function BoxBxLandscape(props: IconProps): JSX.Element
export function BoxBxLaptop(props: IconProps): JSX.Element
export function BoxBxLastPage(props: IconProps): JSX.Element
export function BoxBxLaugh(props: IconProps): JSX.Element
export function BoxBxLayerMinus(props: IconProps): JSX.Element
export function BoxBxLayerPlus(props: IconProps): JSX.Element
export function BoxBxLayer(props: IconProps): JSX.Element
export function BoxBxLayout(props: IconProps): JSX.Element
export function BoxBxLeaf(props: IconProps): JSX.Element
export function BoxBxLeftArrowAlt(props: IconProps): JSX.Element
export function BoxBxLeftArrowCircle(props: IconProps): JSX.Element
export function BoxBxLeftArrow(props: IconProps): JSX.Element
export function BoxBxLeftDownArrowCircle(props: IconProps): JSX.Element
export function BoxBxLeftIndent(props: IconProps): JSX.Element
export function BoxBxLeftTopArrowCircle(props: IconProps): JSX.Element
export function BoxBxLemon(props: IconProps): JSX.Element
export function BoxBxLibrary(props: IconProps): JSX.Element
export function BoxBxLike(props: IconProps): JSX.Element
export function BoxBxLineChartDown(props: IconProps): JSX.Element
export function BoxBxLineChart(props: IconProps): JSX.Element
export function BoxBxLinkAlt(props: IconProps): JSX.Element
export function BoxBxLinkExternal(props: IconProps): JSX.Element
export function BoxBxLink(props: IconProps): JSX.Element
export function BoxBxLira(props: IconProps): JSX.Element
export function BoxBxListCheck(props: IconProps): JSX.Element
export function BoxBxListMinus(props: IconProps): JSX.Element
export function BoxBxListOl(props: IconProps): JSX.Element
export function BoxBxListPlus(props: IconProps): JSX.Element
export function BoxBxListUl(props: IconProps): JSX.Element
export function BoxBxLoaderAlt(props: IconProps): JSX.Element
export function BoxBxLoaderCircle(props: IconProps): JSX.Element
export function BoxBxLoader(props: IconProps): JSX.Element
export function BoxBxLocationPlus(props: IconProps): JSX.Element
export function BoxBxLockAlt(props: IconProps): JSX.Element
export function BoxBxLockOpenAlt(props: IconProps): JSX.Element
export function BoxBxLockOpen(props: IconProps): JSX.Element
export function BoxBxLock(props: IconProps): JSX.Element
export function BoxBxLogInCircle(props: IconProps): JSX.Element
export function BoxBxLogIn(props: IconProps): JSX.Element
export function BoxBxLogOutCircle(props: IconProps): JSX.Element
export function BoxBxLogOut(props: IconProps): JSX.Element
export function BoxBxLowVision(props: IconProps): JSX.Element
export function BoxBxMagnet(props: IconProps): JSX.Element
export function BoxBxMailSend(props: IconProps): JSX.Element
export function BoxBxMaleFemale(props: IconProps): JSX.Element
export function BoxBxMaleSign(props: IconProps): JSX.Element
export function BoxBxMale(props: IconProps): JSX.Element
export function BoxBxMapAlt(props: IconProps): JSX.Element
export function BoxBxMapPin(props: IconProps): JSX.Element
export function BoxBxMap(props: IconProps): JSX.Element
export function BoxBxMask(props: IconProps): JSX.Element
export function BoxBxMath(props: IconProps): JSX.Element
export function BoxBxMedal(props: IconProps): JSX.Element
export function BoxBxMehAlt(props: IconProps): JSX.Element
export function BoxBxMehBlank(props: IconProps): JSX.Element
export function BoxBxMeh(props: IconProps): JSX.Element
export function BoxBxMemoryCard(props: IconProps): JSX.Element
export function BoxBxMenuAltLeft(props: IconProps): JSX.Element
export function BoxBxMenuAltRight(props: IconProps): JSX.Element
export function BoxBxMenu(props: IconProps): JSX.Element
export function BoxBxMerge(props: IconProps): JSX.Element
export function BoxBxMessageAdd(props: IconProps): JSX.Element
export function BoxBxMessageAltAdd(props: IconProps): JSX.Element
export function BoxBxMessageAltCheck(props: IconProps): JSX.Element
export function BoxBxMessageAltDetail(props: IconProps): JSX.Element
export function BoxBxMessageAltDots(props: IconProps): JSX.Element
export function BoxBxMessageAltEdit(props: IconProps): JSX.Element
export function BoxBxMessageAltError(props: IconProps): JSX.Element
export function BoxBxMessageAltMinus(props: IconProps): JSX.Element
export function BoxBxMessageAltX(props: IconProps): JSX.Element
export function BoxBxMessageAlt(props: IconProps): JSX.Element
export function BoxBxMessageCheck(props: IconProps): JSX.Element
export function BoxBxMessageDetail(props: IconProps): JSX.Element
export function BoxBxMessageDots(props: IconProps): JSX.Element
export function BoxBxMessageEdit(props: IconProps): JSX.Element
export function BoxBxMessageError(props: IconProps): JSX.Element
export function BoxBxMessageMinus(props: IconProps): JSX.Element
export function BoxBxMessageRoundedAdd(props: IconProps): JSX.Element
export function BoxBxMessageRoundedCheck(props: IconProps): JSX.Element
export function BoxBxMessageRoundedDetail(props: IconProps): JSX.Element
export function BoxBxMessageRoundedDots(props: IconProps): JSX.Element
export function BoxBxMessageRoundedEdit(props: IconProps): JSX.Element
export function BoxBxMessageRoundedError(props: IconProps): JSX.Element
export function BoxBxMessageRoundedMinus(props: IconProps): JSX.Element
export function BoxBxMessageRoundedX(props: IconProps): JSX.Element
export function BoxBxMessageRounded(props: IconProps): JSX.Element
export function BoxBxMessageSquareAdd(props: IconProps): JSX.Element
export function BoxBxMessageSquareCheck(props: IconProps): JSX.Element
export function BoxBxMessageSquareDetail(props: IconProps): JSX.Element
export function BoxBxMessageSquareDots(props: IconProps): JSX.Element
export function BoxBxMessageSquareEdit(props: IconProps): JSX.Element
export function BoxBxMessageSquareError(props: IconProps): JSX.Element
export function BoxBxMessageSquareMinus(props: IconProps): JSX.Element
export function BoxBxMessageSquareX(props: IconProps): JSX.Element
export function BoxBxMessageSquare(props: IconProps): JSX.Element
export function BoxBxMessageX(props: IconProps): JSX.Element
export function BoxBxMessage(props: IconProps): JSX.Element
export function BoxBxMeteor(props: IconProps): JSX.Element
export function BoxBxMicrochip(props: IconProps): JSX.Element
export function BoxBxMicrophoneOff(props: IconProps): JSX.Element
export function BoxBxMicrophone(props: IconProps): JSX.Element
export function BoxBxMinusBack(props: IconProps): JSX.Element
export function BoxBxMinusCircle(props: IconProps): JSX.Element
export function BoxBxMinusFront(props: IconProps): JSX.Element
export function BoxBxMinus(props: IconProps): JSX.Element
export function BoxBxMobileAlt(props: IconProps): JSX.Element
export function BoxBxMobileLandscape(props: IconProps): JSX.Element
export function BoxBxMobileVibration(props: IconProps): JSX.Element
export function BoxBxMobile(props: IconProps): JSX.Element
export function BoxBxMoneyWithdraw(props: IconProps): JSX.Element
export function BoxBxMoney(props: IconProps): JSX.Element
export function BoxBxMoon(props: IconProps): JSX.Element
export function BoxBxMouseAlt(props: IconProps): JSX.Element
export function BoxBxMouse(props: IconProps): JSX.Element
export function BoxBxMoveHorizontal(props: IconProps): JSX.Element
export function BoxBxMoveVertical(props: IconProps): JSX.Element
export function BoxBxMove(props: IconProps): JSX.Element
export function BoxBxMoviePlay(props: IconProps): JSX.Element
export function BoxBxMovie(props: IconProps): JSX.Element
export function BoxBxMusic(props: IconProps): JSX.Element
export function BoxBxNavigation(props: IconProps): JSX.Element
export function BoxBxNetworkChart(props: IconProps): JSX.Element
export function BoxBxNews(props: IconProps): JSX.Element
export function BoxBxNoEntry(props: IconProps): JSX.Element
export function BoxBxNoSignal(props: IconProps): JSX.Element
export function BoxBxNote(props: IconProps): JSX.Element
export function BoxBxNotepad(props: IconProps): JSX.Element
export function BoxBxNotificationOff(props: IconProps): JSX.Element
export function BoxBxNotification(props: IconProps): JSX.Element
export function BoxBxObjectsHorizontalCenter(props: IconProps): JSX.Element
export function BoxBxObjectsHorizontalLeft(props: IconProps): JSX.Element
export function BoxBxObjectsHorizontalRight(props: IconProps): JSX.Element
export function BoxBxObjectsVerticalBottom(props: IconProps): JSX.Element
export function BoxBxObjectsVerticalCenter(props: IconProps): JSX.Element
export function BoxBxObjectsVerticalTop(props: IconProps): JSX.Element
export function BoxBxOutline(props: IconProps): JSX.Element
export function BoxBxPackage(props: IconProps): JSX.Element
export function BoxBxPaintRoll(props: IconProps): JSX.Element
export function BoxBxPaint(props: IconProps): JSX.Element
export function BoxBxPalette(props: IconProps): JSX.Element
export function BoxBxPaperPlane(props: IconProps): JSX.Element
export function BoxBxPaperclip(props: IconProps): JSX.Element
export function BoxBxParagraph(props: IconProps): JSX.Element
export function BoxBxParty(props: IconProps): JSX.Element
export function BoxBxPaste(props: IconProps): JSX.Element
export function BoxBxPauseCircle(props: IconProps): JSX.Element
export function BoxBxPause(props: IconProps): JSX.Element
export function BoxBxPen(props: IconProps): JSX.Element
export function BoxBxPencil(props: IconProps): JSX.Element
export function BoxBxPhoneCall(props: IconProps): JSX.Element
export function BoxBxPhoneIncoming(props: IconProps): JSX.Element
export function BoxBxPhoneOff(props: IconProps): JSX.Element
export function BoxBxPhoneOutgoing(props: IconProps): JSX.Element
export function BoxBxPhone(props: IconProps): JSX.Element
export function BoxBxPhotoAlbum(props: IconProps): JSX.Element
export function BoxBxPieChartAlt2(props: IconProps): JSX.Element
export function BoxBxPieChartAlt(props: IconProps): JSX.Element
export function BoxBxPieChart(props: IconProps): JSX.Element
export function BoxBxPin(props: IconProps): JSX.Element
export function BoxBxPlanet(props: IconProps): JSX.Element
export function BoxBxPlayCircle(props: IconProps): JSX.Element
export function BoxBxPlay(props: IconProps): JSX.Element
export function BoxBxPlug(props: IconProps): JSX.Element
export function BoxBxPlusCircle(props: IconProps): JSX.Element
export function BoxBxPlusMedical(props: IconProps): JSX.Element
export function BoxBxPlus(props: IconProps): JSX.Element
export function BoxBxPodcast(props: IconProps): JSX.Element
export function BoxBxPointer(props: IconProps): JSX.Element
export function BoxBxPoll(props: IconProps): JSX.Element
export function BoxBxPolygon(props: IconProps): JSX.Element
export function BoxBxPopsicle(props: IconProps): JSX.Element
export function BoxBxPound(props: IconProps): JSX.Element
export function BoxBxPowerOff(props: IconProps): JSX.Element
export function BoxBxPrinter(props: IconProps): JSX.Element
export function BoxBxPulse(props: IconProps): JSX.Element
export function BoxBxPurchaseTagAlt(props: IconProps): JSX.Element
export function BoxBxPurchaseTag(props: IconProps): JSX.Element
export function BoxBxPyramid(props: IconProps): JSX.Element
export function BoxBxQrScan(props: IconProps): JSX.Element
export function BoxBxQr(props: IconProps): JSX.Element
export function BoxBxQuestionMark(props: IconProps): JSX.Element
export function BoxBxRadar(props: IconProps): JSX.Element
export function BoxBxRadioCircleMarked(props: IconProps): JSX.Element
export function BoxBxRadioCircle(props: IconProps): JSX.Element
export function BoxBxRadio(props: IconProps): JSX.Element
export function BoxBxReceipt(props: IconProps): JSX.Element
export function BoxBxRectangle(props: IconProps): JSX.Element
export function BoxBxRecycle(props: IconProps): JSX.Element
export function BoxBxRedo(props: IconProps): JSX.Element
export function BoxBxReflectHorizontal(props: IconProps): JSX.Element
export function BoxBxReflectVertical(props: IconProps): JSX.Element
export function BoxBxRefresh(props: IconProps): JSX.Element
export function BoxBxRegistered(props: IconProps): JSX.Element
export function BoxBxRename(props: IconProps): JSX.Element
export function BoxBxRepeat(props: IconProps): JSX.Element
export function BoxBxReplyAll(props: IconProps): JSX.Element
export function BoxBxReply(props: IconProps): JSX.Element
export function BoxBxRepost(props: IconProps): JSX.Element
export function BoxBxReset(props: IconProps): JSX.Element
export function BoxBxRestaurant(props: IconProps): JSX.Element
export function BoxBxRevision(props: IconProps): JSX.Element
export function BoxBxRewindCircle(props: IconProps): JSX.Element
export function BoxBxRewind(props: IconProps): JSX.Element
export function BoxBxRfid(props: IconProps): JSX.Element
export function BoxBxRightArrowAlt(props: IconProps): JSX.Element
export function BoxBxRightArrowCircle(props: IconProps): JSX.Element
export function BoxBxRightArrow(props: IconProps): JSX.Element
export function BoxBxRightDownArrowCircle(props: IconProps): JSX.Element
export function BoxBxRightIndent(props: IconProps): JSX.Element
export function BoxBxRightTopArrowCircle(props: IconProps): JSX.Element
export function BoxBxRocket(props: IconProps): JSX.Element
export function BoxBxRotateLeft(props: IconProps): JSX.Element
export function BoxBxRotateRight(props: IconProps): JSX.Element
export function BoxBxRss(props: IconProps): JSX.Element
export function BoxBxRuble(props: IconProps): JSX.Element
export function BoxBxRuler(props: IconProps): JSX.Element
export function BoxBxRun(props: IconProps): JSX.Element
export function BoxBxRupee(props: IconProps): JSX.Element
export function BoxBxSad(props: IconProps): JSX.Element
export function BoxBxSave(props: IconProps): JSX.Element
export function BoxBxScan(props: IconProps): JSX.Element
export function BoxBxScatterChart(props: IconProps): JSX.Element
export function BoxBxScreenshot(props: IconProps): JSX.Element
export function BoxBxSearchAlt2(props: IconProps): JSX.Element
export function BoxBxSearchAlt(props: IconProps): JSX.Element
export function BoxBxSearch(props: IconProps): JSX.Element
export function BoxBxSelectMultiple(props: IconProps): JSX.Element
export function BoxBxSelection(props: IconProps): JSX.Element
export function BoxBxSend(props: IconProps): JSX.Element
export function BoxBxServer(props: IconProps): JSX.Element
export function BoxBxShapeCircle(props: IconProps): JSX.Element
export function BoxBxShapePolygon(props: IconProps): JSX.Element
export function BoxBxShapeSquare(props: IconProps): JSX.Element
export function BoxBxShapeTriangle(props: IconProps): JSX.Element
export function BoxBxShareAlt(props: IconProps): JSX.Element
export function BoxBxShare(props: IconProps): JSX.Element
export function BoxBxShekel(props: IconProps): JSX.Element
export function BoxBxShieldAlt2(props: IconProps): JSX.Element
export function BoxBxShieldAlt(props: IconProps): JSX.Element
export function BoxBxShieldMinus(props: IconProps): JSX.Element
export function BoxBxShieldPlus(props: IconProps): JSX.Element
export function BoxBxShieldQuarter(props: IconProps): JSX.Element
export function BoxBxShieldX(props: IconProps): JSX.Element
export function BoxBxShield(props: IconProps): JSX.Element
export function BoxBxShocked(props: IconProps): JSX.Element
export function BoxBxShoppingBag(props: IconProps): JSX.Element
export function BoxBxShowAlt(props: IconProps): JSX.Element
export function BoxBxShow(props: IconProps): JSX.Element
export function BoxBxShower(props: IconProps): JSX.Element
export function BoxBxShuffle(props: IconProps): JSX.Element
export function BoxBxSidebar(props: IconProps): JSX.Element
export function BoxBxSignal1(props: IconProps): JSX.Element
export function BoxBxSignal2(props: IconProps): JSX.Element
export function BoxBxSignal3(props: IconProps): JSX.Element
export function BoxBxSignal4(props: IconProps): JSX.Element
export function BoxBxSignal5(props: IconProps): JSX.Element
export function BoxBxSitemap(props: IconProps): JSX.Element
export function BoxBxSkipNextCircle(props: IconProps): JSX.Element
export function BoxBxSkipNext(props: IconProps): JSX.Element
export function BoxBxSkipPreviousCircle(props: IconProps): JSX.Element
export function BoxBxSkipPrevious(props: IconProps): JSX.Element
export function BoxBxSleepy(props: IconProps): JSX.Element
export function BoxBxSliderAlt(props: IconProps): JSX.Element
export function BoxBxSlider(props: IconProps): JSX.Element
export function BoxBxSlideshow(props: IconProps): JSX.Element
export function BoxBxSmile(props: IconProps): JSX.Element
export function BoxBxSortAZ(props: IconProps): JSX.Element
export function BoxBxSortAlt2(props: IconProps): JSX.Element
export function BoxBxSortDown(props: IconProps): JSX.Element
export function BoxBxSortUp(props: IconProps): JSX.Element
export function BoxBxSortZA(props: IconProps): JSX.Element
export function BoxBxSort(props: IconProps): JSX.Element
export function BoxBxSpa(props: IconProps): JSX.Element
export function BoxBxSpaceBar(props: IconProps): JSX.Element
export function BoxBxSpeaker(props: IconProps): JSX.Element
export function BoxBxSprayCan(props: IconProps): JSX.Element
export function BoxBxSpreadsheet(props: IconProps): JSX.Element
export function BoxBxSquareRounded(props: IconProps): JSX.Element
export function BoxBxSquare(props: IconProps): JSX.Element
export function BoxBxStar(props: IconProps): JSX.Element
export function BoxBxStation(props: IconProps): JSX.Element
export function BoxBxStats(props: IconProps): JSX.Element
export function BoxBxSticker(props: IconProps): JSX.Element
export function BoxBxStopCircle(props: IconProps): JSX.Element
export function BoxBxStop(props: IconProps): JSX.Element
export function BoxBxStopwatch(props: IconProps): JSX.Element
export function BoxBxStoreAlt(props: IconProps): JSX.Element
export function BoxBxStore(props: IconProps): JSX.Element
export function BoxBxStreetView(props: IconProps): JSX.Element
export function BoxBxStrikethrough(props: IconProps): JSX.Element
export function BoxBxSubdirectoryLeft(props: IconProps): JSX.Element
export function BoxBxSubdirectoryRight(props: IconProps): JSX.Element
export function BoxBxSun(props: IconProps): JSX.Element
export function BoxBxSupport(props: IconProps): JSX.Element
export function BoxBxSushi(props: IconProps): JSX.Element
export function BoxBxSwim(props: IconProps): JSX.Element
export function BoxBxSync(props: IconProps): JSX.Element
export function BoxBxTab(props: IconProps): JSX.Element
export function BoxBxTable(props: IconProps): JSX.Element
export function BoxBxTachometer(props: IconProps): JSX.Element
export function BoxBxTagAlt(props: IconProps): JSX.Element
export function BoxBxTag(props: IconProps): JSX.Element
export function BoxBxTargetLock(props: IconProps): JSX.Element
export function BoxBxTaskX(props: IconProps): JSX.Element
export function BoxBxTask(props: IconProps): JSX.Element
export function BoxBxTaxi(props: IconProps): JSX.Element
export function BoxBxTennisBall(props: IconProps): JSX.Element
export function BoxBxTerminal(props: IconProps): JSX.Element
export function BoxBxTestTube(props: IconProps): JSX.Element
export function BoxBxText(props: IconProps): JSX.Element
export function BoxBxTimeFive(props: IconProps): JSX.Element
export function BoxBxTime(props: IconProps): JSX.Element
export function BoxBxTimer(props: IconProps): JSX.Element
export function BoxBxTired(props: IconProps): JSX.Element
export function BoxBxToggleLeft(props: IconProps): JSX.Element
export function BoxBxToggleRight(props: IconProps): JSX.Element
export function BoxBxTone(props: IconProps): JSX.Element
export function BoxBxTrafficCone(props: IconProps): JSX.Element
export function BoxBxTrain(props: IconProps): JSX.Element
export function BoxBxTransferAlt(props: IconProps): JSX.Element
export function BoxBxTransfer(props: IconProps): JSX.Element
export function BoxBxTrashAlt(props: IconProps): JSX.Element
export function BoxBxTrash(props: IconProps): JSX.Element
export function BoxBxTrendingDown(props: IconProps): JSX.Element
export function BoxBxTrendingUp(props: IconProps): JSX.Element
export function BoxBxTrim(props: IconProps): JSX.Element
export function BoxBxTrip(props: IconProps): JSX.Element
export function BoxBxTrophy(props: IconProps): JSX.Element
export function BoxBxTv(props: IconProps): JSX.Element
export function BoxBxUnderline(props: IconProps): JSX.Element
export function BoxBxUndo(props: IconProps): JSX.Element
export function BoxBxUnite(props: IconProps): JSX.Element
export function BoxBxUniversalAccess(props: IconProps): JSX.Element
export function BoxBxUnlink(props: IconProps): JSX.Element
export function BoxBxUpArrowAlt(props: IconProps): JSX.Element
export function BoxBxUpArrowCircle(props: IconProps): JSX.Element
export function BoxBxUpArrow(props: IconProps): JSX.Element
export function BoxBxUpload(props: IconProps): JSX.Element
export function BoxBxUpsideDown(props: IconProps): JSX.Element
export function BoxBxUpvote(props: IconProps): JSX.Element
export function BoxBxUsb(props: IconProps): JSX.Element
export function BoxBxUserCheck(props: IconProps): JSX.Element
export function BoxBxUserCircle(props: IconProps): JSX.Element
export function BoxBxUserMinus(props: IconProps): JSX.Element
export function BoxBxUserPin(props: IconProps): JSX.Element
export function BoxBxUserPlus(props: IconProps): JSX.Element
export function BoxBxUserVoice(props: IconProps): JSX.Element
export function BoxBxUserX(props: IconProps): JSX.Element
export function BoxBxUser(props: IconProps): JSX.Element
export function BoxBxVector(props: IconProps): JSX.Element
export function BoxBxVerticalBottom(props: IconProps): JSX.Element
export function BoxBxVerticalCenter(props: IconProps): JSX.Element
export function BoxBxVerticalTop(props: IconProps): JSX.Element
export function BoxBxVial(props: IconProps): JSX.Element
export function BoxBxVideoOff(props: IconProps): JSX.Element
export function BoxBxVideoPlus(props: IconProps): JSX.Element
export function BoxBxVideoRecording(props: IconProps): JSX.Element
export function BoxBxVideo(props: IconProps): JSX.Element
export function BoxBxVoicemail(props: IconProps): JSX.Element
export function BoxBxVolumeFull(props: IconProps): JSX.Element
export function BoxBxVolumeLow(props: IconProps): JSX.Element
export function BoxBxVolumeMute(props: IconProps): JSX.Element
export function BoxBxVolume(props: IconProps): JSX.Element
export function BoxBxWalk(props: IconProps): JSX.Element
export function BoxBxWalletAlt(props: IconProps): JSX.Element
export function BoxBxWallet(props: IconProps): JSX.Element
export function BoxBxWater(props: IconProps): JSX.Element
export function BoxBxWebcam(props: IconProps): JSX.Element
export function BoxBxWifi0(props: IconProps): JSX.Element
export function BoxBxWifi1(props: IconProps): JSX.Element
export function BoxBxWifi2(props: IconProps): JSX.Element
export function BoxBxWifiOff(props: IconProps): JSX.Element
export function BoxBxWifi(props: IconProps): JSX.Element
export function BoxBxWind(props: IconProps): JSX.Element
export function BoxBxWindowAlt(props: IconProps): JSX.Element
export function BoxBxWindowClose(props: IconProps): JSX.Element
export function BoxBxWindowOpen(props: IconProps): JSX.Element
export function BoxBxWindow(props: IconProps): JSX.Element
export function BoxBxWindows(props: IconProps): JSX.Element
export function BoxBxWine(props: IconProps): JSX.Element
export function BoxBxWinkSmile(props: IconProps): JSX.Element
export function BoxBxWinkTongue(props: IconProps): JSX.Element
export function BoxBxWon(props: IconProps): JSX.Element
export function BoxBxWorld(props: IconProps): JSX.Element
export function BoxBxWrench(props: IconProps): JSX.Element
export function BoxBxXCircle(props: IconProps): JSX.Element
export function BoxBxX(props: IconProps): JSX.Element
export function BoxBxYen(props: IconProps): JSX.Element
export function BoxBxZoomIn(props: IconProps): JSX.Element
export function BoxBxZoomOut(props: IconProps): JSX.Element
