// AUTO-GENERATED FILE. DO NOT EDIT BY HAND.
// Icon set: codicons | License: MIT (MIT_URL)
import type { JSX } from 'solid-js'
import type { IconProps } from './/types'

export function CodiconAccount(props: IconProps): JSX.Element
export function CodiconActivateBreakpoints(props: IconProps): JSX.Element
export function CodiconAdd(props: IconProps): JSX.Element
export function CodiconArchive(props: IconProps): JSX.Element
export function CodiconArrowBoth(props: IconProps): JSX.Element
export function CodiconArrowCircleDown(props: IconProps): JSX.Element
export function CodiconArrowCircleLeft(props: IconProps): JSX.Element
export function CodiconArrowCircleRight(props: IconProps): JSX.Element
export function CodiconArrowCircleUp(props: IconProps): JSX.Element
export function CodiconArrowDown(props: IconProps): JSX.Element
export function CodiconArrowLeft(props: IconProps): JSX.Element
export function CodiconArrowRight(props: IconProps): JSX.Element
export function CodiconArrowSmallDown(props: IconProps): JSX.Element
export function CodiconArrowSmallLeft(props: IconProps): JSX.Element
export function CodiconArrowSmallRight(props: IconProps): JSX.Element
export function CodiconArrowSmallUp(props: IconProps): JSX.Element
export function CodiconArrowSwap(props: IconProps): JSX.Element
export function CodiconArrowUp(props: IconProps): JSX.Element
export function CodiconAttach(props: IconProps): JSX.Element
export function CodiconAzureDevops(props: IconProps): JSX.Element
export function CodiconAzure(props: IconProps): JSX.Element
export function CodiconBeakerStop(props: IconProps): JSX.Element
export function CodiconBeaker(props: IconProps): JSX.Element
export function CodiconBellDot(props: IconProps): JSX.Element
export function CodiconBellSlashDot(props: IconProps): JSX.Element
export function CodiconBellSlash(props: IconProps): JSX.Element
export function CodiconBell(props: IconProps): JSX.Element
export function CodiconBlank(props: IconProps): JSX.Element
export function CodiconBold(props: IconProps): JSX.Element
export function CodiconBook(props: IconProps): JSX.Element
export function CodiconBookmark(props: IconProps): JSX.Element
export function CodiconBracketDot(props: IconProps): JSX.Element
export function CodiconBracketError(props: IconProps): JSX.Element
export function CodiconBriefcase(props: IconProps): JSX.Element
export function CodiconBroadcast(props: IconProps): JSX.Element
export function CodiconBrowser(props: IconProps): JSX.Element
export function CodiconBug(props: IconProps): JSX.Element
export function CodiconCalendar(props: IconProps): JSX.Element
export function CodiconCallIncoming(props: IconProps): JSX.Element
export function CodiconCallOutgoing(props: IconProps): JSX.Element
export function CodiconCaseSensitive(props: IconProps): JSX.Element
export function CodiconChatSparkle(props: IconProps): JSX.Element
export function CodiconCheckAll(props: IconProps): JSX.Element
export function CodiconCheck(props: IconProps): JSX.Element
export function CodiconChecklist(props: IconProps): JSX.Element
export function CodiconChevronDown(props: IconProps): JSX.Element
export function CodiconChevronLeft(props: IconProps): JSX.Element
export function CodiconChevronRight(props: IconProps): JSX.Element
export function CodiconChevronUp(props: IconProps): JSX.Element
export function CodiconChip(props: IconProps): JSX.Element
export function CodiconChromeClose(props: IconProps): JSX.Element
export function CodiconChromeMaximize(props: IconProps): JSX.Element
export function CodiconChromeMinimize(props: IconProps): JSX.Element
export function CodiconChromeRestore(props: IconProps): JSX.Element
export function CodiconCircleFilled(props: IconProps): JSX.Element
export function CodiconCircleLargeFilled(props: IconProps): JSX.Element
export function CodiconCircleLarge(props: IconProps): JSX.Element
export function CodiconCircleSlash(props: IconProps): JSX.Element
export function CodiconCircleSmallFilled(props: IconProps): JSX.Element
export function CodiconCircleSmall(props: IconProps): JSX.Element
export function CodiconCircle(props: IconProps): JSX.Element
export function CodiconCircuitBoard(props: IconProps): JSX.Element
export function CodiconClearAll(props: IconProps): JSX.Element
export function CodiconClippy(props: IconProps): JSX.Element
export function CodiconCloseAll(props: IconProps): JSX.Element
export function CodiconClose(props: IconProps): JSX.Element
export function CodiconCloudDownload(props: IconProps): JSX.Element
export function CodiconCloudUpload(props: IconProps): JSX.Element
export function CodiconCloud(props: IconProps): JSX.Element
export function CodiconCodeOss(props: IconProps): JSX.Element
export function CodiconCodeReview(props: IconProps): JSX.Element
export function CodiconCode(props: IconProps): JSX.Element
export function CodiconCoffee(props: IconProps): JSX.Element
export function CodiconCollapseAll(props: IconProps): JSX.Element
export function CodiconColorMode(props: IconProps): JSX.Element
export function CodiconCombine(props: IconProps): JSX.Element
export function CodiconCommentDiscussion(props: IconProps): JSX.Element
export function CodiconCommentDraft(props: IconProps): JSX.Element
export function CodiconCommentUnresolved(props: IconProps): JSX.Element
export function CodiconComment(props: IconProps): JSX.Element
export function CodiconCompassActive(props: IconProps): JSX.Element
export function CodiconCompassDot(props: IconProps): JSX.Element
export function CodiconCompass(props: IconProps): JSX.Element
export function CodiconCopilotBlocked(props: IconProps): JSX.Element
export function CodiconCopilotError(props: IconProps): JSX.Element
export function CodiconCopilotInProgress(props: IconProps): JSX.Element
export function CodiconCopilotLarge(props: IconProps): JSX.Element
export function CodiconCopilotNotConnected(props: IconProps): JSX.Element
export function CodiconCopilotSuccess(props: IconProps): JSX.Element
export function CodiconCopilotUnavailable(props: IconProps): JSX.Element
export function CodiconCopilotWarningLarge(props: IconProps): JSX.Element
export function CodiconCopilotWarning(props: IconProps): JSX.Element
export function CodiconCopilot(props: IconProps): JSX.Element
export function CodiconCopy(props: IconProps): JSX.Element
export function CodiconCoverage(props: IconProps): JSX.Element
export function CodiconCreditCard(props: IconProps): JSX.Element
export function CodiconDash(props: IconProps): JSX.Element
export function CodiconDashboard(props: IconProps): JSX.Element
export function CodiconDatabase(props: IconProps): JSX.Element
export function CodiconDebugAll(props: IconProps): JSX.Element
export function CodiconDebugAltSmall(props: IconProps): JSX.Element
export function CodiconDebugAlt(props: IconProps): JSX.Element
export function CodiconDebugBreakpointConditionalUnverified(props: IconProps): JSX.Element
export function CodiconDebugBreakpointConditional(props: IconProps): JSX.Element
export function CodiconDebugBreakpointDataUnverified(props: IconProps): JSX.Element
export function CodiconDebugBreakpointData(props: IconProps): JSX.Element
export function CodiconDebugBreakpointFunctionUnverified(props: IconProps): JSX.Element
export function CodiconDebugBreakpointFunction(props: IconProps): JSX.Element
export function CodiconDebugBreakpointLogUnverified(props: IconProps): JSX.Element
export function CodiconDebugBreakpointLog(props: IconProps): JSX.Element
export function CodiconDebugBreakpointUnsupported(props: IconProps): JSX.Element
export function CodiconDebugConsole(props: IconProps): JSX.Element
export function CodiconDebugContinueSmall(props: IconProps): JSX.Element
export function CodiconDebugContinue(props: IconProps): JSX.Element
export function CodiconDebugCoverage(props: IconProps): JSX.Element
export function CodiconDebugDisconnect(props: IconProps): JSX.Element
export function CodiconDebugLineByLine(props: IconProps): JSX.Element
export function CodiconDebugPause(props: IconProps): JSX.Element
export function CodiconDebugRerun(props: IconProps): JSX.Element
export function CodiconDebugRestartFrame(props: IconProps): JSX.Element
export function CodiconDebugRestart(props: IconProps): JSX.Element
export function CodiconDebugReverseContinue(props: IconProps): JSX.Element
export function CodiconDebugStackframeActive(props: IconProps): JSX.Element
export function CodiconDebugStackframe(props: IconProps): JSX.Element
export function CodiconDebugStart(props: IconProps): JSX.Element
export function CodiconDebugStepBack(props: IconProps): JSX.Element
export function CodiconDebugStepInto(props: IconProps): JSX.Element
export function CodiconDebugStepOut(props: IconProps): JSX.Element
export function CodiconDebugStepOver(props: IconProps): JSX.Element
export function CodiconDebugStop(props: IconProps): JSX.Element
export function CodiconDebug(props: IconProps): JSX.Element
export function CodiconDesktopDownload(props: IconProps): JSX.Element
export function CodiconDeviceCameraVideo(props: IconProps): JSX.Element
export function CodiconDeviceCamera(props: IconProps): JSX.Element
export function CodiconDeviceMobile(props: IconProps): JSX.Element
export function CodiconDiffAdded(props: IconProps): JSX.Element
export function CodiconDiffIgnored(props: IconProps): JSX.Element
export function CodiconDiffModified(props: IconProps): JSX.Element
export function CodiconDiffMultiple(props: IconProps): JSX.Element
export function CodiconDiffRemoved(props: IconProps): JSX.Element
export function CodiconDiffRenamed(props: IconProps): JSX.Element
export function CodiconDiffSingle(props: IconProps): JSX.Element
export function CodiconDiff(props: IconProps): JSX.Element
export function CodiconDiscard(props: IconProps): JSX.Element
export function CodiconEditSession(props: IconProps): JSX.Element
export function CodiconEditSparkle(props: IconProps): JSX.Element
export function CodiconEdit(props: IconProps): JSX.Element
export function CodiconEditorLayout(props: IconProps): JSX.Element
export function CodiconEllipsis(props: IconProps): JSX.Element
export function CodiconEmptyWindow(props: IconProps): JSX.Element
export function CodiconErrorSmall(props: IconProps): JSX.Element
export function CodiconError(props: IconProps): JSX.Element
export function CodiconExclude(props: IconProps): JSX.Element
export function CodiconExpandAll(props: IconProps): JSX.Element
export function CodiconExport(props: IconProps): JSX.Element
export function CodiconExtensionsLarge(props: IconProps): JSX.Element
export function CodiconExtensions(props: IconProps): JSX.Element
export function CodiconEyeClosed(props: IconProps): JSX.Element
export function CodiconEye(props: IconProps): JSX.Element
export function CodiconFeedback(props: IconProps): JSX.Element
export function CodiconFileBinary(props: IconProps): JSX.Element
export function CodiconFileCode(props: IconProps): JSX.Element
export function CodiconFileMedia(props: IconProps): JSX.Element
export function CodiconFilePdf(props: IconProps): JSX.Element
export function CodiconFileSubmodule(props: IconProps): JSX.Element
export function CodiconFileSymlinkDirectory(props: IconProps): JSX.Element
export function CodiconFileSymlinkFile(props: IconProps): JSX.Element
export function CodiconFileZip(props: IconProps): JSX.Element
export function CodiconFile(props: IconProps): JSX.Element
export function CodiconFiles(props: IconProps): JSX.Element
export function CodiconFilterFilled(props: IconProps): JSX.Element
export function CodiconFilter(props: IconProps): JSX.Element
export function CodiconFlag(props: IconProps): JSX.Element
export function CodiconFlame(props: IconProps): JSX.Element
export function CodiconFoldDown(props: IconProps): JSX.Element
export function CodiconFoldUp(props: IconProps): JSX.Element
export function CodiconFold(props: IconProps): JSX.Element
export function CodiconFolderActive(props: IconProps): JSX.Element
export function CodiconFolderLibrary(props: IconProps): JSX.Element
export function CodiconFolderOpened(props: IconProps): JSX.Element
export function CodiconFolder(props: IconProps): JSX.Element
export function CodiconGame(props: IconProps): JSX.Element
export function CodiconGear(props: IconProps): JSX.Element
export function CodiconGift(props: IconProps): JSX.Element
export function CodiconGistSecret(props: IconProps): JSX.Element
export function CodiconGist(props: IconProps): JSX.Element
export function CodiconGitCommit(props: IconProps): JSX.Element
export function CodiconGitCompare(props: IconProps): JSX.Element
export function CodiconGitFetch(props: IconProps): JSX.Element
export function CodiconGitMerge(props: IconProps): JSX.Element
export function CodiconGitPullRequestClosed(props: IconProps): JSX.Element
export function CodiconGitPullRequestCreate(props: IconProps): JSX.Element
export function CodiconGitPullRequestDone(props: IconProps): JSX.Element
export function CodiconGitPullRequestDraft(props: IconProps): JSX.Element
export function CodiconGitPullRequestGoToChanges(props: IconProps): JSX.Element
export function CodiconGitPullRequestNewChanges(props: IconProps): JSX.Element
export function CodiconGitPullRequest(props: IconProps): JSX.Element
export function CodiconGitStashApply(props: IconProps): JSX.Element
export function CodiconGitStashPop(props: IconProps): JSX.Element
export function CodiconGitStash(props: IconProps): JSX.Element
export function CodiconGithubAction(props: IconProps): JSX.Element
export function CodiconGithubAlt(props: IconProps): JSX.Element
export function CodiconGithubInverted(props: IconProps): JSX.Element
export function CodiconGithubProject(props: IconProps): JSX.Element
export function CodiconGithub(props: IconProps): JSX.Element
export function CodiconGlobe(props: IconProps): JSX.Element
export function CodiconGoToEditingSession(props: IconProps): JSX.Element
export function CodiconGoToFile(props: IconProps): JSX.Element
export function CodiconGoToSearch(props: IconProps): JSX.Element
export function CodiconGrabber(props: IconProps): JSX.Element
export function CodiconGraphLeft(props: IconProps): JSX.Element
export function CodiconGraphLine(props: IconProps): JSX.Element
export function CodiconGraphScatter(props: IconProps): JSX.Element
export function CodiconGraph(props: IconProps): JSX.Element
export function CodiconGripper(props: IconProps): JSX.Element
export function CodiconGroupByRefType(props: IconProps): JSX.Element
export function CodiconHeartFilled(props: IconProps): JSX.Element
export function CodiconHeart(props: IconProps): JSX.Element
export function CodiconHistory(props: IconProps): JSX.Element
export function CodiconHome(props: IconProps): JSX.Element
export function CodiconHorizontalRule(props: IconProps): JSX.Element
export function CodiconHubot(props: IconProps): JSX.Element
export function CodiconInbox(props: IconProps): JSX.Element
export function CodiconIndent(props: IconProps): JSX.Element
export function CodiconInfo(props: IconProps): JSX.Element
export function CodiconInsert(props: IconProps): JSX.Element
export function CodiconInspect(props: IconProps): JSX.Element
export function CodiconIssueDraft(props: IconProps): JSX.Element
export function CodiconIssueReopened(props: IconProps): JSX.Element
export function CodiconIssues(props: IconProps): JSX.Element
export function CodiconItalic(props: IconProps): JSX.Element
export function CodiconJersey(props: IconProps): JSX.Element
export function CodiconJson(props: IconProps): JSX.Element
export function CodiconKebabVertical(props: IconProps): JSX.Element
export function CodiconKey(props: IconProps): JSX.Element
export function CodiconKeyboardTabAbove(props: IconProps): JSX.Element
export function CodiconKeyboardTabBelow(props: IconProps): JSX.Element
export function CodiconKeyboardTab(props: IconProps): JSX.Element
export function CodiconLaw(props: IconProps): JSX.Element
export function CodiconLayersActive(props: IconProps): JSX.Element
export function CodiconLayersDot(props: IconProps): JSX.Element
export function CodiconLayers(props: IconProps): JSX.Element
export function CodiconLayoutActivitybarLeft(props: IconProps): JSX.Element
export function CodiconLayoutActivitybarRight(props: IconProps): JSX.Element
export function CodiconLayoutCentered(props: IconProps): JSX.Element
export function CodiconLayoutMenubar(props: IconProps): JSX.Element
export function CodiconLayoutPanelCenter(props: IconProps): JSX.Element
export function CodiconLayoutPanelDock(props: IconProps): JSX.Element
export function CodiconLayoutPanelJustify(props: IconProps): JSX.Element
export function CodiconLayoutPanelLeft(props: IconProps): JSX.Element
export function CodiconLayoutPanelOff(props: IconProps): JSX.Element
export function CodiconLayoutPanelRight(props: IconProps): JSX.Element
export function CodiconLayoutPanel(props: IconProps): JSX.Element
export function CodiconLayoutSidebarLeftDock(props: IconProps): JSX.Element
export function CodiconLayoutSidebarLeftOff(props: IconProps): JSX.Element
export function CodiconLayoutSidebarLeft(props: IconProps): JSX.Element
export function CodiconLayoutSidebarRightDock(props: IconProps): JSX.Element
export function CodiconLayoutSidebarRightOff(props: IconProps): JSX.Element
export function CodiconLayoutSidebarRight(props: IconProps): JSX.Element
export function CodiconLayoutStatusbar(props: IconProps): JSX.Element
export function CodiconLayout(props: IconProps): JSX.Element
export function CodiconLibrary(props: IconProps): JSX.Element
export function CodiconLightbulbAutofix(props: IconProps): JSX.Element
export function CodiconLightbulbEmpty(props: IconProps): JSX.Element
export function CodiconLightbulbSparkle(props: IconProps): JSX.Element
export function CodiconLightbulb(props: IconProps): JSX.Element
export function CodiconLinkExternal(props: IconProps): JSX.Element
export function CodiconLink(props: IconProps): JSX.Element
export function CodiconListFilter(props: IconProps): JSX.Element
export function CodiconListFlat(props: IconProps): JSX.Element
export function CodiconListOrdered(props: IconProps): JSX.Element
export function CodiconListSelection(props: IconProps): JSX.Element
export function CodiconListTree(props: IconProps): JSX.Element
export function CodiconListUnordered(props: IconProps): JSX.Element
export function CodiconLiveShare(props: IconProps): JSX.Element
export function CodiconLoading(props: IconProps): JSX.Element
export function CodiconLocation(props: IconProps): JSX.Element
export function CodiconLockSmall(props: IconProps): JSX.Element
export function CodiconLock(props: IconProps): JSX.Element
export function CodiconMagnet(props: IconProps): JSX.Element
export function CodiconMailRead(props: IconProps): JSX.Element
export function CodiconMail(props: IconProps): JSX.Element
export function CodiconMapFilled(props: IconProps): JSX.Element
export function CodiconMapVerticalFilled(props: IconProps): JSX.Element
export function CodiconMapVertical(props: IconProps): JSX.Element
export function CodiconMap(props: IconProps): JSX.Element
export function CodiconMarkdown(props: IconProps): JSX.Element
export function CodiconMcp(props: IconProps): JSX.Element
export function CodiconMegaphone(props: IconProps): JSX.Element
export function CodiconMention(props: IconProps): JSX.Element
export function CodiconMenu(props: IconProps): JSX.Element
export function CodiconMerge(props: IconProps): JSX.Element
export function CodiconMicFilled(props: IconProps): JSX.Element
export function CodiconMic(props: IconProps): JSX.Element
export function CodiconMilestone(props: IconProps): JSX.Element
export function CodiconMirror(props: IconProps): JSX.Element
export function CodiconMortarBoard(props: IconProps): JSX.Element
export function CodiconMove(props: IconProps): JSX.Element
export function CodiconMultipleWindows(props: IconProps): JSX.Element
export function CodiconMusic(props: IconProps): JSX.Element
export function CodiconMute(props: IconProps): JSX.Element
export function CodiconNewFile(props: IconProps): JSX.Element
export function CodiconNewFolder(props: IconProps): JSX.Element
export function CodiconNewline(props: IconProps): JSX.Element
export function CodiconNoNewline(props: IconProps): JSX.Element
export function CodiconNote(props: IconProps): JSX.Element
export function CodiconNotebookTemplate(props: IconProps): JSX.Element
export function CodiconNotebook(props: IconProps): JSX.Element
export function CodiconOctoface(props: IconProps): JSX.Element
export function CodiconOpenPreview(props: IconProps): JSX.Element
export function CodiconOrganization(props: IconProps): JSX.Element
export function CodiconOutput(props: IconProps): JSX.Element
export function CodiconPackage(props: IconProps): JSX.Element
export function CodiconPaintcan(props: IconProps): JSX.Element
export function CodiconPassFilled(props: IconProps): JSX.Element
export function CodiconPass(props: IconProps): JSX.Element
export function CodiconPercentage(props: IconProps): JSX.Element
export function CodiconPersonAdd(props: IconProps): JSX.Element
export function CodiconPerson(props: IconProps): JSX.Element
export function CodiconPiano(props: IconProps): JSX.Element
export function CodiconPieChart(props: IconProps): JSX.Element
export function CodiconPin(props: IconProps): JSX.Element
export function CodiconPinnedDirty(props: IconProps): JSX.Element
export function CodiconPinned(props: IconProps): JSX.Element
export function CodiconPlayCircle(props: IconProps): JSX.Element
export function CodiconPlay(props: IconProps): JSX.Element
export function CodiconPlug(props: IconProps): JSX.Element
export function CodiconPreserveCase(props: IconProps): JSX.Element
export function CodiconPreview(props: IconProps): JSX.Element
export function CodiconPrimitiveSquare(props: IconProps): JSX.Element
export function CodiconProject(props: IconProps): JSX.Element
export function CodiconPulse(props: IconProps): JSX.Element
export function CodiconPython(props: IconProps): JSX.Element
export function CodiconQuestion(props: IconProps): JSX.Element
export function CodiconQuote(props: IconProps): JSX.Element
export function CodiconRadioTower(props: IconProps): JSX.Element
export function CodiconReactions(props: IconProps): JSX.Element
export function CodiconRecordKeys(props: IconProps): JSX.Element
export function CodiconRecordSmall(props: IconProps): JSX.Element
export function CodiconRecord(props: IconProps): JSX.Element
export function CodiconRedo(props: IconProps): JSX.Element
export function CodiconReferences(props: IconProps): JSX.Element
export function CodiconRefresh(props: IconProps): JSX.Element
export function CodiconRegex(props: IconProps): JSX.Element
export function CodiconRemoteExplorer(props: IconProps): JSX.Element
export function CodiconRemote(props: IconProps): JSX.Element
export function CodiconRemove(props: IconProps): JSX.Element
export function CodiconReplaceAll(props: IconProps): JSX.Element
export function CodiconReplace(props: IconProps): JSX.Element
export function CodiconReply(props: IconProps): JSX.Element
export function CodiconRepoClone(props: IconProps): JSX.Element
export function CodiconRepoFetch(props: IconProps): JSX.Element
export function CodiconRepoForcePush(props: IconProps): JSX.Element
export function CodiconRepoForked(props: IconProps): JSX.Element
export function CodiconRepoPinned(props: IconProps): JSX.Element
export function CodiconRepoPull(props: IconProps): JSX.Element
export function CodiconRepoPush(props: IconProps): JSX.Element
export function CodiconRepo(props: IconProps): JSX.Element
export function CodiconReport(props: IconProps): JSX.Element
export function CodiconRequestChanges(props: IconProps): JSX.Element
export function CodiconRobot(props: IconProps): JSX.Element
export function CodiconRocket(props: IconProps): JSX.Element
export function CodiconRootFolderOpened(props: IconProps): JSX.Element
export function CodiconRootFolder(props: IconProps): JSX.Element
export function CodiconRss(props: IconProps): JSX.Element
export function CodiconRuby(props: IconProps): JSX.Element
export function CodiconRunAbove(props: IconProps): JSX.Element
export function CodiconRunAllCoverage(props: IconProps): JSX.Element
export function CodiconRunAll(props: IconProps): JSX.Element
export function CodiconRunBelow(props: IconProps): JSX.Element
export function CodiconRunCoverage(props: IconProps): JSX.Element
export function CodiconRunErrors(props: IconProps): JSX.Element
export function CodiconSaveAll(props: IconProps): JSX.Element
export function CodiconSaveAs(props: IconProps): JSX.Element
export function CodiconSave(props: IconProps): JSX.Element
export function CodiconScreenFull(props: IconProps): JSX.Element
export function CodiconScreenNormal(props: IconProps): JSX.Element
export function CodiconSearchFuzzy(props: IconProps): JSX.Element
export function CodiconSearchSparkle(props: IconProps): JSX.Element
export function CodiconSearchStop(props: IconProps): JSX.Element
export function CodiconSearch(props: IconProps): JSX.Element
export function CodiconSend(props: IconProps): JSX.Element
export function CodiconServerEnvironment(props: IconProps): JSX.Element
export function CodiconServerProcess(props: IconProps): JSX.Element
export function CodiconServer(props: IconProps): JSX.Element
export function CodiconSettingsGear(props: IconProps): JSX.Element
export function CodiconSettings(props: IconProps): JSX.Element
export function CodiconShare(props: IconProps): JSX.Element
export function CodiconShield(props: IconProps): JSX.Element
export function CodiconSignIn(props: IconProps): JSX.Element
export function CodiconSignOut(props: IconProps): JSX.Element
export function CodiconSmiley(props: IconProps): JSX.Element
export function CodiconSnake(props: IconProps): JSX.Element
export function CodiconSortPrecedence(props: IconProps): JSX.Element
export function CodiconSourceControl(props: IconProps): JSX.Element
export function CodiconSparkleFilled(props: IconProps): JSX.Element
export function CodiconSparkle(props: IconProps): JSX.Element
export function CodiconSplitHorizontal(props: IconProps): JSX.Element
export function CodiconSplitVertical(props: IconProps): JSX.Element
export function CodiconSquirrel(props: IconProps): JSX.Element
export function CodiconStarEmpty(props: IconProps): JSX.Element
export function CodiconStarFull(props: IconProps): JSX.Element
export function CodiconStarHalf(props: IconProps): JSX.Element
export function CodiconStopCircle(props: IconProps): JSX.Element
export function CodiconSurroundWith(props: IconProps): JSX.Element
export function CodiconSymbolArray(props: IconProps): JSX.Element
export function CodiconSymbolBoolean(props: IconProps): JSX.Element
export function CodiconSymbolClass(props: IconProps): JSX.Element
export function CodiconSymbolColor(props: IconProps): JSX.Element
export function CodiconSymbolConstant(props: IconProps): JSX.Element
export function CodiconSymbolEnumMember(props: IconProps): JSX.Element
export function CodiconSymbolEnum(props: IconProps): JSX.Element
export function CodiconSymbolEvent(props: IconProps): JSX.Element
export function CodiconSymbolField(props: IconProps): JSX.Element
export function CodiconSymbolFile(props: IconProps): JSX.Element
export function CodiconSymbolInterface(props: IconProps): JSX.Element
export function CodiconSymbolKey(props: IconProps): JSX.Element
export function CodiconSymbolKeyword(props: IconProps): JSX.Element
export function CodiconSymbolMethodArrow(props: IconProps): JSX.Element
export function CodiconSymbolMethod(props: IconProps): JSX.Element
export function CodiconSymbolMisc(props: IconProps): JSX.Element
export function CodiconSymbolNamespace(props: IconProps): JSX.Element
export function CodiconSymbolNumeric(props: IconProps): JSX.Element
export function CodiconSymbolOperator(props: IconProps): JSX.Element
export function CodiconSymbolParameter(props: IconProps): JSX.Element
export function CodiconSymbolProperty(props: IconProps): JSX.Element
export function CodiconSymbolRuler(props: IconProps): JSX.Element
export function CodiconSymbolSnippet(props: IconProps): JSX.Element
export function CodiconSymbolString(props: IconProps): JSX.Element
export function CodiconSymbolStructure(props: IconProps): JSX.Element
export function CodiconSymbolVariable(props: IconProps): JSX.Element
export function CodiconSyncIgnored(props: IconProps): JSX.Element
export function CodiconSync(props: IconProps): JSX.Element
export function CodiconTable(props: IconProps): JSX.Element
export function CodiconTag(props: IconProps): JSX.Element
export function CodiconTarget(props: IconProps): JSX.Element
export function CodiconTasklist(props: IconProps): JSX.Element
export function CodiconTelescope(props: IconProps): JSX.Element
export function CodiconTerminalBash(props: IconProps): JSX.Element
export function CodiconTerminalCmd(props: IconProps): JSX.Element
export function CodiconTerminalDebian(props: IconProps): JSX.Element
export function CodiconTerminalLinux(props: IconProps): JSX.Element
export function CodiconTerminalPowershell(props: IconProps): JSX.Element
export function CodiconTerminalTmux(props: IconProps): JSX.Element
export function CodiconTerminalUbuntu(props: IconProps): JSX.Element
export function CodiconTerminal(props: IconProps): JSX.Element
export function CodiconTextSize(props: IconProps): JSX.Element
export function CodiconThreeBars(props: IconProps): JSX.Element
export function CodiconThumbsdownFilled(props: IconProps): JSX.Element
export function CodiconThumbsdown(props: IconProps): JSX.Element
export function CodiconThumbsupFilled(props: IconProps): JSX.Element
export function CodiconThumbsup(props: IconProps): JSX.Element
export function CodiconTools(props: IconProps): JSX.Element
export function CodiconTrash(props: IconProps): JSX.Element
export function CodiconTriangleDown(props: IconProps): JSX.Element
export function CodiconTriangleLeft(props: IconProps): JSX.Element
export function CodiconTriangleRight(props: IconProps): JSX.Element
export function CodiconTriangleUp(props: IconProps): JSX.Element
export function CodiconTwitter(props: IconProps): JSX.Element
export function CodiconTypeHierarchySub(props: IconProps): JSX.Element
export function CodiconTypeHierarchySuper(props: IconProps): JSX.Element
export function CodiconTypeHierarchy(props: IconProps): JSX.Element
export function CodiconUnfold(props: IconProps): JSX.Element
export function CodiconUngroupByRefType(props: IconProps): JSX.Element
export function CodiconUnlock(props: IconProps): JSX.Element
export function CodiconUnmute(props: IconProps): JSX.Element
export function CodiconUnverified(props: IconProps): JSX.Element
export function CodiconVariableGroup(props: IconProps): JSX.Element
export function CodiconVerifiedFilled(props: IconProps): JSX.Element
export function CodiconVerified(props: IconProps): JSX.Element
export function CodiconVersions(props: IconProps): JSX.Element
export function CodiconVmActive(props: IconProps): JSX.Element
export function CodiconVmConnect(props: IconProps): JSX.Element
export function CodiconVmOutline(props: IconProps): JSX.Element
export function CodiconVmRunning(props: IconProps): JSX.Element
export function CodiconVm(props: IconProps): JSX.Element
export function CodiconVr(props: IconProps): JSX.Element
export function CodiconVscodeInsiders(props: IconProps): JSX.Element
export function CodiconVscode(props: IconProps): JSX.Element
export function CodiconWand(props: IconProps): JSX.Element
export function CodiconWarning(props: IconProps): JSX.Element
export function CodiconWatch(props: IconProps): JSX.Element
export function CodiconWhitespace(props: IconProps): JSX.Element
export function CodiconWholeWord(props: IconProps): JSX.Element
export function CodiconWindow(props: IconProps): JSX.Element
export function CodiconWordWrap(props: IconProps): JSX.Element
export function CodiconWorkspaceTrusted(props: IconProps): JSX.Element
export function CodiconWorkspaceUnknown(props: IconProps): JSX.Element
export function CodiconWorkspaceUntrusted(props: IconProps): JSX.Element
export function CodiconZoomIn(props: IconProps): JSX.Element
export function CodiconZoomOut(props: IconProps): JSX.Element
