// AUTO-GENERATED FILE. DO NOT EDIT BY HAND.
// Icon set: feather | License: MIT (MIT_URL)
import type { JSX } from 'solid-js'
import type { IconProps } from './/types'

export function FeatherActivity(props: IconProps): JSX.Element
export function FeatherAirplay(props: IconProps): JSX.Element
export function FeatherAlertCircle(props: IconProps): JSX.Element
export function FeatherAlertOctagon(props: IconProps): JSX.Element
export function FeatherAlertTriangle(props: IconProps): JSX.Element
export function FeatherAlignCenter(props: IconProps): JSX.Element
export function FeatherAlignJustify(props: IconProps): JSX.Element
export function FeatherAlignLeft(props: IconProps): JSX.Element
export function FeatherAlignRight(props: IconProps): JSX.Element
export function FeatherAnchor(props: IconProps): JSX.Element
export function FeatherAperture(props: IconProps): JSX.Element
export function FeatherArchive(props: IconProps): JSX.Element
export function FeatherArrowDownCircle(props: IconProps): JSX.Element
export function FeatherArrowDownLeft(props: IconProps): JSX.Element
export function FeatherArrowDownRight(props: IconProps): JSX.Element
export function FeatherArrowDown(props: IconProps): JSX.Element
export function FeatherArrowLeftCircle(props: IconProps): JSX.Element
export function FeatherArrowLeft(props: IconProps): JSX.Element
export function FeatherArrowRightCircle(props: IconProps): JSX.Element
export function FeatherArrowRight(props: IconProps): JSX.Element
export function FeatherArrowUpCircle(props: IconProps): JSX.Element
export function FeatherArrowUpLeft(props: IconProps): JSX.Element
export function FeatherArrowUpRight(props: IconProps): JSX.Element
export function FeatherArrowUp(props: IconProps): JSX.Element
export function FeatherAtSign(props: IconProps): JSX.Element
export function FeatherAward(props: IconProps): JSX.Element
export function FeatherBarChart2(props: IconProps): JSX.Element
export function FeatherBarChart(props: IconProps): JSX.Element
export function FeatherBatteryCharging(props: IconProps): JSX.Element
export function FeatherBattery(props: IconProps): JSX.Element
export function FeatherBellOff(props: IconProps): JSX.Element
export function FeatherBell(props: IconProps): JSX.Element
export function FeatherBluetooth(props: IconProps): JSX.Element
export function FeatherBold(props: IconProps): JSX.Element
export function FeatherBookOpen(props: IconProps): JSX.Element
export function FeatherBook(props: IconProps): JSX.Element
export function FeatherBookmark(props: IconProps): JSX.Element
export function FeatherBox(props: IconProps): JSX.Element
export function FeatherBriefcase(props: IconProps): JSX.Element
export function FeatherCalendar(props: IconProps): JSX.Element
export function FeatherCameraOff(props: IconProps): JSX.Element
export function FeatherCamera(props: IconProps): JSX.Element
export function FeatherCast(props: IconProps): JSX.Element
export function FeatherCheckCircle(props: IconProps): JSX.Element
export function FeatherCheckSquare(props: IconProps): JSX.Element
export function FeatherCheck(props: IconProps): JSX.Element
export function FeatherChevronDown(props: IconProps): JSX.Element
export function FeatherChevronLeft(props: IconProps): JSX.Element
export function FeatherChevronRight(props: IconProps): JSX.Element
export function FeatherChevronUp(props: IconProps): JSX.Element
export function FeatherChevronsDown(props: IconProps): JSX.Element
export function FeatherChevronsLeft(props: IconProps): JSX.Element
export function FeatherChevronsRight(props: IconProps): JSX.Element
export function FeatherChevronsUp(props: IconProps): JSX.Element
export function FeatherChrome(props: IconProps): JSX.Element
export function FeatherCircle(props: IconProps): JSX.Element
export function FeatherClipboard(props: IconProps): JSX.Element
export function FeatherClock(props: IconProps): JSX.Element
export function FeatherCloudDrizzle(props: IconProps): JSX.Element
export function FeatherCloudLightning(props: IconProps): JSX.Element
export function FeatherCloudOff(props: IconProps): JSX.Element
export function FeatherCloudRain(props: IconProps): JSX.Element
export function FeatherCloudSnow(props: IconProps): JSX.Element
export function FeatherCloud(props: IconProps): JSX.Element
export function FeatherCode(props: IconProps): JSX.Element
export function FeatherCodepen(props: IconProps): JSX.Element
export function FeatherCodesandbox(props: IconProps): JSX.Element
export function FeatherCoffee(props: IconProps): JSX.Element
export function FeatherColumns(props: IconProps): JSX.Element
export function FeatherCommand(props: IconProps): JSX.Element
export function FeatherCompass(props: IconProps): JSX.Element
export function FeatherCopy(props: IconProps): JSX.Element
export function FeatherCornerDownLeft(props: IconProps): JSX.Element
export function FeatherCornerDownRight(props: IconProps): JSX.Element
export function FeatherCornerLeftDown(props: IconProps): JSX.Element
export function FeatherCornerLeftUp(props: IconProps): JSX.Element
export function FeatherCornerRightDown(props: IconProps): JSX.Element
export function FeatherCornerRightUp(props: IconProps): JSX.Element
export function FeatherCornerUpLeft(props: IconProps): JSX.Element
export function FeatherCornerUpRight(props: IconProps): JSX.Element
export function FeatherCpu(props: IconProps): JSX.Element
export function FeatherCreditCard(props: IconProps): JSX.Element
export function FeatherCrop(props: IconProps): JSX.Element
export function FeatherCrosshair(props: IconProps): JSX.Element
export function FeatherDatabase(props: IconProps): JSX.Element
export function FeatherDelete(props: IconProps): JSX.Element
export function FeatherDisc(props: IconProps): JSX.Element
export function FeatherDivideCircle(props: IconProps): JSX.Element
export function FeatherDivideSquare(props: IconProps): JSX.Element
export function FeatherDivide(props: IconProps): JSX.Element
export function FeatherDollarSign(props: IconProps): JSX.Element
export function FeatherDownloadCloud(props: IconProps): JSX.Element
export function FeatherDownload(props: IconProps): JSX.Element
export function FeatherDribbble(props: IconProps): JSX.Element
export function FeatherDroplet(props: IconProps): JSX.Element
export function FeatherEdit2(props: IconProps): JSX.Element
export function FeatherEdit3(props: IconProps): JSX.Element
export function FeatherEdit(props: IconProps): JSX.Element
export function FeatherExternalLink(props: IconProps): JSX.Element
export function FeatherEyeOff(props: IconProps): JSX.Element
export function FeatherEye(props: IconProps): JSX.Element
export function FeatherFacebook(props: IconProps): JSX.Element
export function FeatherFastForward(props: IconProps): JSX.Element
export function FeatherFeather(props: IconProps): JSX.Element
export function FeatherFigma(props: IconProps): JSX.Element
export function FeatherFileMinus(props: IconProps): JSX.Element
export function FeatherFilePlus(props: IconProps): JSX.Element
export function FeatherFileText(props: IconProps): JSX.Element
export function FeatherFile(props: IconProps): JSX.Element
export function FeatherFilm(props: IconProps): JSX.Element
export function FeatherFilter(props: IconProps): JSX.Element
export function FeatherFlag(props: IconProps): JSX.Element
export function FeatherFolderMinus(props: IconProps): JSX.Element
export function FeatherFolderPlus(props: IconProps): JSX.Element
export function FeatherFolder(props: IconProps): JSX.Element
export function FeatherFramer(props: IconProps): JSX.Element
export function FeatherFrown(props: IconProps): JSX.Element
export function FeatherGift(props: IconProps): JSX.Element
export function FeatherGitBranch(props: IconProps): JSX.Element
export function FeatherGitCommit(props: IconProps): JSX.Element
export function FeatherGitMerge(props: IconProps): JSX.Element
export function FeatherGitPullRequest(props: IconProps): JSX.Element
export function FeatherGithub(props: IconProps): JSX.Element
export function FeatherGitlab(props: IconProps): JSX.Element
export function FeatherGlobe(props: IconProps): JSX.Element
export function FeatherGrid(props: IconProps): JSX.Element
export function FeatherHardDrive(props: IconProps): JSX.Element
export function FeatherHash(props: IconProps): JSX.Element
export function FeatherHeadphones(props: IconProps): JSX.Element
export function FeatherHeart(props: IconProps): JSX.Element
export function FeatherHelpCircle(props: IconProps): JSX.Element
export function FeatherHexagon(props: IconProps): JSX.Element
export function FeatherHome(props: IconProps): JSX.Element
export function FeatherImage(props: IconProps): JSX.Element
export function FeatherInbox(props: IconProps): JSX.Element
export function FeatherInfo(props: IconProps): JSX.Element
export function FeatherInstagram(props: IconProps): JSX.Element
export function FeatherItalic(props: IconProps): JSX.Element
export function FeatherKey(props: IconProps): JSX.Element
export function FeatherLayers(props: IconProps): JSX.Element
export function FeatherLayout(props: IconProps): JSX.Element
export function FeatherLifeBuoy(props: IconProps): JSX.Element
export function FeatherLink2(props: IconProps): JSX.Element
export function FeatherLink(props: IconProps): JSX.Element
export function FeatherLinkedin(props: IconProps): JSX.Element
export function FeatherList(props: IconProps): JSX.Element
export function FeatherLoader(props: IconProps): JSX.Element
export function FeatherLock(props: IconProps): JSX.Element
export function FeatherLogIn(props: IconProps): JSX.Element
export function FeatherLogOut(props: IconProps): JSX.Element
export function FeatherMail(props: IconProps): JSX.Element
export function FeatherMapPin(props: IconProps): JSX.Element
export function FeatherMap(props: IconProps): JSX.Element
export function FeatherMaximize2(props: IconProps): JSX.Element
export function FeatherMaximize(props: IconProps): JSX.Element
export function FeatherMeh(props: IconProps): JSX.Element
export function FeatherMenu(props: IconProps): JSX.Element
export function FeatherMessageCircle(props: IconProps): JSX.Element
export function FeatherMessageSquare(props: IconProps): JSX.Element
export function FeatherMicOff(props: IconProps): JSX.Element
export function FeatherMic(props: IconProps): JSX.Element
export function FeatherMinimize2(props: IconProps): JSX.Element
export function FeatherMinimize(props: IconProps): JSX.Element
export function FeatherMinusCircle(props: IconProps): JSX.Element
export function FeatherMinusSquare(props: IconProps): JSX.Element
export function FeatherMinus(props: IconProps): JSX.Element
export function FeatherMonitor(props: IconProps): JSX.Element
export function FeatherMoon(props: IconProps): JSX.Element
export function FeatherMoreHorizontal(props: IconProps): JSX.Element
export function FeatherMoreVertical(props: IconProps): JSX.Element
export function FeatherMousePointer(props: IconProps): JSX.Element
export function FeatherMove(props: IconProps): JSX.Element
export function FeatherMusic(props: IconProps): JSX.Element
export function FeatherNavigation2(props: IconProps): JSX.Element
export function FeatherNavigation(props: IconProps): JSX.Element
export function FeatherOctagon(props: IconProps): JSX.Element
export function FeatherPackage(props: IconProps): JSX.Element
export function FeatherPaperclip(props: IconProps): JSX.Element
export function FeatherPauseCircle(props: IconProps): JSX.Element
export function FeatherPause(props: IconProps): JSX.Element
export function FeatherPenTool(props: IconProps): JSX.Element
export function FeatherPercent(props: IconProps): JSX.Element
export function FeatherPhoneCall(props: IconProps): JSX.Element
export function FeatherPhoneForwarded(props: IconProps): JSX.Element
export function FeatherPhoneIncoming(props: IconProps): JSX.Element
export function FeatherPhoneMissed(props: IconProps): JSX.Element
export function FeatherPhoneOff(props: IconProps): JSX.Element
export function FeatherPhoneOutgoing(props: IconProps): JSX.Element
export function FeatherPhone(props: IconProps): JSX.Element
export function FeatherPieChart(props: IconProps): JSX.Element
export function FeatherPlayCircle(props: IconProps): JSX.Element
export function FeatherPlay(props: IconProps): JSX.Element
export function FeatherPlusCircle(props: IconProps): JSX.Element
export function FeatherPlusSquare(props: IconProps): JSX.Element
export function FeatherPlus(props: IconProps): JSX.Element
export function FeatherPocket(props: IconProps): JSX.Element
export function FeatherPower(props: IconProps): JSX.Element
export function FeatherPrinter(props: IconProps): JSX.Element
export function FeatherRadio(props: IconProps): JSX.Element
export function FeatherRefreshCcw(props: IconProps): JSX.Element
export function FeatherRefreshCw(props: IconProps): JSX.Element
export function FeatherRepeat(props: IconProps): JSX.Element
export function FeatherRewind(props: IconProps): JSX.Element
export function FeatherRotateCcw(props: IconProps): JSX.Element
export function FeatherRotateCw(props: IconProps): JSX.Element
export function FeatherRss(props: IconProps): JSX.Element
export function FeatherSave(props: IconProps): JSX.Element
export function FeatherScissors(props: IconProps): JSX.Element
export function FeatherSearch(props: IconProps): JSX.Element
export function FeatherSend(props: IconProps): JSX.Element
export function FeatherServer(props: IconProps): JSX.Element
export function FeatherSettings(props: IconProps): JSX.Element
export function FeatherShare2(props: IconProps): JSX.Element
export function FeatherShare(props: IconProps): JSX.Element
export function FeatherShieldOff(props: IconProps): JSX.Element
export function FeatherShield(props: IconProps): JSX.Element
export function FeatherShoppingBag(props: IconProps): JSX.Element
export function FeatherShoppingCart(props: IconProps): JSX.Element
export function FeatherShuffle(props: IconProps): JSX.Element
export function FeatherSidebar(props: IconProps): JSX.Element
export function FeatherSkipBack(props: IconProps): JSX.Element
export function FeatherSkipForward(props: IconProps): JSX.Element
export function FeatherSlack(props: IconProps): JSX.Element
export function FeatherSlash(props: IconProps): JSX.Element
export function FeatherSliders(props: IconProps): JSX.Element
export function FeatherSmartphone(props: IconProps): JSX.Element
export function FeatherSmile(props: IconProps): JSX.Element
export function FeatherSpeaker(props: IconProps): JSX.Element
export function FeatherSquare(props: IconProps): JSX.Element
export function FeatherStar(props: IconProps): JSX.Element
export function FeatherStopCircle(props: IconProps): JSX.Element
export function FeatherSun(props: IconProps): JSX.Element
export function FeatherSunrise(props: IconProps): JSX.Element
export function FeatherSunset(props: IconProps): JSX.Element
export function FeatherTable(props: IconProps): JSX.Element
export function FeatherTablet(props: IconProps): JSX.Element
export function FeatherTag(props: IconProps): JSX.Element
export function FeatherTarget(props: IconProps): JSX.Element
export function FeatherTerminal(props: IconProps): JSX.Element
export function FeatherThermometer(props: IconProps): JSX.Element
export function FeatherThumbsDown(props: IconProps): JSX.Element
export function FeatherThumbsUp(props: IconProps): JSX.Element
export function FeatherToggleLeft(props: IconProps): JSX.Element
export function FeatherToggleRight(props: IconProps): JSX.Element
export function FeatherTool(props: IconProps): JSX.Element
export function FeatherTrash2(props: IconProps): JSX.Element
export function FeatherTrash(props: IconProps): JSX.Element
export function FeatherTrello(props: IconProps): JSX.Element
export function FeatherTrendingDown(props: IconProps): JSX.Element
export function FeatherTrendingUp(props: IconProps): JSX.Element
export function FeatherTriangle(props: IconProps): JSX.Element
export function FeatherTruck(props: IconProps): JSX.Element
export function FeatherTv(props: IconProps): JSX.Element
export function FeatherTwitch(props: IconProps): JSX.Element
export function FeatherTwitter(props: IconProps): JSX.Element
export function FeatherType(props: IconProps): JSX.Element
export function FeatherUmbrella(props: IconProps): JSX.Element
export function FeatherUnderline(props: IconProps): JSX.Element
export function FeatherUnlock(props: IconProps): JSX.Element
export function FeatherUploadCloud(props: IconProps): JSX.Element
export function FeatherUpload(props: IconProps): JSX.Element
export function FeatherUserCheck(props: IconProps): JSX.Element
export function FeatherUserMinus(props: IconProps): JSX.Element
export function FeatherUserPlus(props: IconProps): JSX.Element
export function FeatherUserX(props: IconProps): JSX.Element
export function FeatherUser(props: IconProps): JSX.Element
export function FeatherUsers(props: IconProps): JSX.Element
export function FeatherVideoOff(props: IconProps): JSX.Element
export function FeatherVideo(props: IconProps): JSX.Element
export function FeatherVoicemail(props: IconProps): JSX.Element
export function FeatherVolume1(props: IconProps): JSX.Element
export function FeatherVolume2(props: IconProps): JSX.Element
export function FeatherVolumeX(props: IconProps): JSX.Element
export function FeatherVolume(props: IconProps): JSX.Element
export function FeatherWatch(props: IconProps): JSX.Element
export function FeatherWifiOff(props: IconProps): JSX.Element
export function FeatherWifi(props: IconProps): JSX.Element
export function FeatherWind(props: IconProps): JSX.Element
export function FeatherXCircle(props: IconProps): JSX.Element
export function FeatherXOctagon(props: IconProps): JSX.Element
export function FeatherXSquare(props: IconProps): JSX.Element
export function FeatherX(props: IconProps): JSX.Element
export function FeatherYoutube(props: IconProps): JSX.Element
export function FeatherZapOff(props: IconProps): JSX.Element
export function FeatherZap(props: IconProps): JSX.Element
export function FeatherZoomIn(props: IconProps): JSX.Element
export function FeatherZoomOut(props: IconProps): JSX.Element
