// AUTO-GENERATED FILE. DO NOT EDIT BY HAND.
// Icon set: heroicons | License: MIT (MIT_URL)
import type { JSX } from 'solid-js'
import type { IconProps } from './/types'

export function HeroAcademicCap(props: IconProps): JSX.Element
export function HeroAdjustmentsHorizontal(props: IconProps): JSX.Element
export function HeroAdjustmentsVertical(props: IconProps): JSX.Element
export function HeroArchiveBoxArrowDown(props: IconProps): JSX.Element
export function HeroArchiveBoxXMark(props: IconProps): JSX.Element
export function HeroArchiveBox(props: IconProps): JSX.Element
export function HeroArrowDownCircle(props: IconProps): JSX.Element
export function HeroArrowDownLeft(props: IconProps): JSX.Element
export function HeroArrowDownOnSquareStack(props: IconProps): JSX.Element
export function HeroArrowDownOnSquare(props: IconProps): JSX.Element
export function HeroArrowDownRight(props: IconProps): JSX.Element
export function HeroArrowDownTray(props: IconProps): JSX.Element
export function HeroArrowDown(props: IconProps): JSX.Element
export function HeroArrowLeftCircle(props: IconProps): JSX.Element
export function HeroArrowLeftEndOnRectangle(props: IconProps): JSX.Element
export function HeroArrowLeftOnRectangle(props: IconProps): JSX.Element
export function HeroArrowLeftStartOnRectangle(props: IconProps): JSX.Element
export function HeroArrowLeft(props: IconProps): JSX.Element
export function HeroArrowLongDown(props: IconProps): JSX.Element
export function HeroArrowLongLeft(props: IconProps): JSX.Element
export function HeroArrowLongRight(props: IconProps): JSX.Element
export function HeroArrowLongUp(props: IconProps): JSX.Element
export function HeroArrowPathRoundedSquare(props: IconProps): JSX.Element
export function HeroArrowPath(props: IconProps): JSX.Element
export function HeroArrowRightCircle(props: IconProps): JSX.Element
export function HeroArrowRightEndOnRectangle(props: IconProps): JSX.Element
export function HeroArrowRightOnRectangle(props: IconProps): JSX.Element
export function HeroArrowRightStartOnRectangle(props: IconProps): JSX.Element
export function HeroArrowRight(props: IconProps): JSX.Element
export function HeroArrowSmallDown(props: IconProps): JSX.Element
export function HeroArrowSmallLeft(props: IconProps): JSX.Element
export function HeroArrowSmallRight(props: IconProps): JSX.Element
export function HeroArrowSmallUp(props: IconProps): JSX.Element
export function HeroArrowTopRightOnSquare(props: IconProps): JSX.Element
export function HeroArrowTrendingDown(props: IconProps): JSX.Element
export function HeroArrowTrendingUp(props: IconProps): JSX.Element
export function HeroArrowTurnDownLeft(props: IconProps): JSX.Element
export function HeroArrowTurnDownRight(props: IconProps): JSX.Element
export function HeroArrowTurnLeftDown(props: IconProps): JSX.Element
export function HeroArrowTurnLeftUp(props: IconProps): JSX.Element
export function HeroArrowTurnRightDown(props: IconProps): JSX.Element
export function HeroArrowTurnRightUp(props: IconProps): JSX.Element
export function HeroArrowTurnUpLeft(props: IconProps): JSX.Element
export function HeroArrowTurnUpRight(props: IconProps): JSX.Element
export function HeroArrowUpCircle(props: IconProps): JSX.Element
export function HeroArrowUpLeft(props: IconProps): JSX.Element
export function HeroArrowUpOnSquareStack(props: IconProps): JSX.Element
export function HeroArrowUpOnSquare(props: IconProps): JSX.Element
export function HeroArrowUpRight(props: IconProps): JSX.Element
export function HeroArrowUpTray(props: IconProps): JSX.Element
export function HeroArrowUp(props: IconProps): JSX.Element
export function HeroArrowUturnDown(props: IconProps): JSX.Element
export function HeroArrowUturnLeft(props: IconProps): JSX.Element
export function HeroArrowUturnRight(props: IconProps): JSX.Element
export function HeroArrowUturnUp(props: IconProps): JSX.Element
export function HeroArrowsPointingIn(props: IconProps): JSX.Element
export function HeroArrowsPointingOut(props: IconProps): JSX.Element
export function HeroArrowsRightLeft(props: IconProps): JSX.Element
export function HeroArrowsUpDown(props: IconProps): JSX.Element
export function HeroAtSymbol(props: IconProps): JSX.Element
export function HeroBackspace(props: IconProps): JSX.Element
export function HeroBackward(props: IconProps): JSX.Element
export function HeroBanknotes(props: IconProps): JSX.Element
export function HeroBars2(props: IconProps): JSX.Element
export function HeroBars3BottomLeft(props: IconProps): JSX.Element
export function HeroBars3BottomRight(props: IconProps): JSX.Element
export function HeroBars3CenterLeft(props: IconProps): JSX.Element
export function HeroBars3(props: IconProps): JSX.Element
export function HeroBars4(props: IconProps): JSX.Element
export function HeroBarsArrowDown(props: IconProps): JSX.Element
export function HeroBarsArrowUp(props: IconProps): JSX.Element
export function HeroBattery0(props: IconProps): JSX.Element
export function HeroBattery100(props: IconProps): JSX.Element
export function HeroBattery50(props: IconProps): JSX.Element
export function HeroBeaker(props: IconProps): JSX.Element
export function HeroBellAlert(props: IconProps): JSX.Element
export function HeroBellSlash(props: IconProps): JSX.Element
export function HeroBellSnooze(props: IconProps): JSX.Element
export function HeroBell(props: IconProps): JSX.Element
export function HeroBold(props: IconProps): JSX.Element
export function HeroBoltSlash(props: IconProps): JSX.Element
export function HeroBolt(props: IconProps): JSX.Element
export function HeroBookOpen(props: IconProps): JSX.Element
export function HeroBookmarkSlash(props: IconProps): JSX.Element
export function HeroBookmarkSquare(props: IconProps): JSX.Element
export function HeroBookmark(props: IconProps): JSX.Element
export function HeroBriefcase(props: IconProps): JSX.Element
export function HeroBugAnt(props: IconProps): JSX.Element
export function HeroBuildingLibrary(props: IconProps): JSX.Element
export function HeroBuildingOffice2(props: IconProps): JSX.Element
export function HeroBuildingOffice(props: IconProps): JSX.Element
export function HeroBuildingStorefront(props: IconProps): JSX.Element
export function HeroCake(props: IconProps): JSX.Element
export function HeroCalculator(props: IconProps): JSX.Element
export function HeroCalendarDateRange(props: IconProps): JSX.Element
export function HeroCalendarDays(props: IconProps): JSX.Element
export function HeroCalendar(props: IconProps): JSX.Element
export function HeroCamera(props: IconProps): JSX.Element
export function HeroChartBarSquare(props: IconProps): JSX.Element
export function HeroChartBar(props: IconProps): JSX.Element
export function HeroChartPie(props: IconProps): JSX.Element
export function HeroChatBubbleBottomCenterText(props: IconProps): JSX.Element
export function HeroChatBubbleBottomCenter(props: IconProps): JSX.Element
export function HeroChatBubbleLeftEllipsis(props: IconProps): JSX.Element
export function HeroChatBubbleLeftRight(props: IconProps): JSX.Element
export function HeroChatBubbleLeft(props: IconProps): JSX.Element
export function HeroChatBubbleOvalLeftEllipsis(props: IconProps): JSX.Element
export function HeroChatBubbleOvalLeft(props: IconProps): JSX.Element
export function HeroCheckBadge(props: IconProps): JSX.Element
export function HeroCheckCircle(props: IconProps): JSX.Element
export function HeroCheck(props: IconProps): JSX.Element
export function HeroChevronDoubleDown(props: IconProps): JSX.Element
export function HeroChevronDoubleLeft(props: IconProps): JSX.Element
export function HeroChevronDoubleRight(props: IconProps): JSX.Element
export function HeroChevronDoubleUp(props: IconProps): JSX.Element
export function HeroChevronDown(props: IconProps): JSX.Element
export function HeroChevronLeft(props: IconProps): JSX.Element
export function HeroChevronRight(props: IconProps): JSX.Element
export function HeroChevronUpDown(props: IconProps): JSX.Element
export function HeroChevronUp(props: IconProps): JSX.Element
export function HeroCircleStack(props: IconProps): JSX.Element
export function HeroClipboardDocumentCheck(props: IconProps): JSX.Element
export function HeroClipboardDocumentList(props: IconProps): JSX.Element
export function HeroClipboardDocument(props: IconProps): JSX.Element
export function HeroClipboard(props: IconProps): JSX.Element
export function HeroClock(props: IconProps): JSX.Element
export function HeroCloudArrowDown(props: IconProps): JSX.Element
export function HeroCloudArrowUp(props: IconProps): JSX.Element
export function HeroCloud(props: IconProps): JSX.Element
export function HeroCodeBracketSquare(props: IconProps): JSX.Element
export function HeroCodeBracket(props: IconProps): JSX.Element
export function HeroCog6Tooth(props: IconProps): JSX.Element
export function HeroCog8Tooth(props: IconProps): JSX.Element
export function HeroCog(props: IconProps): JSX.Element
export function HeroCommandLine(props: IconProps): JSX.Element
export function HeroComputerDesktop(props: IconProps): JSX.Element
export function HeroCpuChip(props: IconProps): JSX.Element
export function HeroCreditCard(props: IconProps): JSX.Element
export function HeroCubeTransparent(props: IconProps): JSX.Element
export function HeroCube(props: IconProps): JSX.Element
export function HeroCurrencyBangladeshi(props: IconProps): JSX.Element
export function HeroCurrencyDollar(props: IconProps): JSX.Element
export function HeroCurrencyEuro(props: IconProps): JSX.Element
export function HeroCurrencyPound(props: IconProps): JSX.Element
export function HeroCurrencyRupee(props: IconProps): JSX.Element
export function HeroCurrencyYen(props: IconProps): JSX.Element
export function HeroCursorArrowRays(props: IconProps): JSX.Element
export function HeroCursorArrowRipple(props: IconProps): JSX.Element
export function HeroDevicePhoneMobile(props: IconProps): JSX.Element
export function HeroDeviceTablet(props: IconProps): JSX.Element
export function HeroDivide(props: IconProps): JSX.Element
export function HeroDocumentArrowDown(props: IconProps): JSX.Element
export function HeroDocumentArrowUp(props: IconProps): JSX.Element
export function HeroDocumentChartBar(props: IconProps): JSX.Element
export function HeroDocumentCheck(props: IconProps): JSX.Element
export function HeroDocumentCurrencyBangladeshi(props: IconProps): JSX.Element
export function HeroDocumentCurrencyDollar(props: IconProps): JSX.Element
export function HeroDocumentCurrencyEuro(props: IconProps): JSX.Element
export function HeroDocumentCurrencyPound(props: IconProps): JSX.Element
export function HeroDocumentCurrencyRupee(props: IconProps): JSX.Element
export function HeroDocumentCurrencyYen(props: IconProps): JSX.Element
export function HeroDocumentDuplicate(props: IconProps): JSX.Element
export function HeroDocumentMagnifyingGlass(props: IconProps): JSX.Element
export function HeroDocumentMinus(props: IconProps): JSX.Element
export function HeroDocumentPlus(props: IconProps): JSX.Element
export function HeroDocumentText(props: IconProps): JSX.Element
export function HeroDocument(props: IconProps): JSX.Element
export function HeroEllipsisHorizontalCircle(props: IconProps): JSX.Element
export function HeroEllipsisHorizontal(props: IconProps): JSX.Element
export function HeroEllipsisVertical(props: IconProps): JSX.Element
export function HeroEnvelopeOpen(props: IconProps): JSX.Element
export function HeroEnvelope(props: IconProps): JSX.Element
export function HeroEquals(props: IconProps): JSX.Element
export function HeroExclamationCircle(props: IconProps): JSX.Element
export function HeroExclamationTriangle(props: IconProps): JSX.Element
export function HeroEyeDropper(props: IconProps): JSX.Element
export function HeroEyeSlash(props: IconProps): JSX.Element
export function HeroEye(props: IconProps): JSX.Element
export function HeroFaceFrown(props: IconProps): JSX.Element
export function HeroFaceSmile(props: IconProps): JSX.Element
export function HeroFilm(props: IconProps): JSX.Element
export function HeroFingerPrint(props: IconProps): JSX.Element
export function HeroFire(props: IconProps): JSX.Element
export function HeroFlag(props: IconProps): JSX.Element
export function HeroFolderArrowDown(props: IconProps): JSX.Element
export function HeroFolderMinus(props: IconProps): JSX.Element
export function HeroFolderOpen(props: IconProps): JSX.Element
export function HeroFolderPlus(props: IconProps): JSX.Element
export function HeroFolder(props: IconProps): JSX.Element
export function HeroForward(props: IconProps): JSX.Element
export function HeroFunnel(props: IconProps): JSX.Element
export function HeroGif(props: IconProps): JSX.Element
export function HeroGiftTop(props: IconProps): JSX.Element
export function HeroGift(props: IconProps): JSX.Element
export function HeroGlobeAlt(props: IconProps): JSX.Element
export function HeroGlobeAmericas(props: IconProps): JSX.Element
export function HeroGlobeAsiaAustralia(props: IconProps): JSX.Element
export function HeroGlobeEuropeAfrica(props: IconProps): JSX.Element
export function HeroH1(props: IconProps): JSX.Element
export function HeroH2(props: IconProps): JSX.Element
export function HeroH3(props: IconProps): JSX.Element
export function HeroHandRaised(props: IconProps): JSX.Element
export function HeroHandThumbDown(props: IconProps): JSX.Element
export function HeroHandThumbUp(props: IconProps): JSX.Element
export function HeroHashtag(props: IconProps): JSX.Element
export function HeroHeart(props: IconProps): JSX.Element
export function HeroHomeModern(props: IconProps): JSX.Element
export function HeroHome(props: IconProps): JSX.Element
export function HeroIdentification(props: IconProps): JSX.Element
export function HeroInboxArrowDown(props: IconProps): JSX.Element
export function HeroInboxStack(props: IconProps): JSX.Element
export function HeroInbox(props: IconProps): JSX.Element
export function HeroInformationCircle(props: IconProps): JSX.Element
export function HeroItalic(props: IconProps): JSX.Element
export function HeroKey(props: IconProps): JSX.Element
export function HeroLanguage(props: IconProps): JSX.Element
export function HeroLifebuoy(props: IconProps): JSX.Element
export function HeroLightBulb(props: IconProps): JSX.Element
export function HeroLinkSlash(props: IconProps): JSX.Element
export function HeroLink(props: IconProps): JSX.Element
export function HeroListBullet(props: IconProps): JSX.Element
export function HeroLockClosed(props: IconProps): JSX.Element
export function HeroLockOpen(props: IconProps): JSX.Element
export function HeroMagnifyingGlassCircle(props: IconProps): JSX.Element
export function HeroMagnifyingGlassMinus(props: IconProps): JSX.Element
export function HeroMagnifyingGlassPlus(props: IconProps): JSX.Element
export function HeroMagnifyingGlass(props: IconProps): JSX.Element
export function HeroMapPin(props: IconProps): JSX.Element
export function HeroMap(props: IconProps): JSX.Element
export function HeroMegaphone(props: IconProps): JSX.Element
export function HeroMicrophone(props: IconProps): JSX.Element
export function HeroMinusCircle(props: IconProps): JSX.Element
export function HeroMinusSmall(props: IconProps): JSX.Element
export function HeroMinus(props: IconProps): JSX.Element
export function HeroMoon(props: IconProps): JSX.Element
export function HeroMusicalNote(props: IconProps): JSX.Element
export function HeroNewspaper(props: IconProps): JSX.Element
export function HeroNoSymbol(props: IconProps): JSX.Element
export function HeroNumberedList(props: IconProps): JSX.Element
export function HeroPaintBrush(props: IconProps): JSX.Element
export function HeroPaperAirplane(props: IconProps): JSX.Element
export function HeroPaperClip(props: IconProps): JSX.Element
export function HeroPauseCircle(props: IconProps): JSX.Element
export function HeroPause(props: IconProps): JSX.Element
export function HeroPencilSquare(props: IconProps): JSX.Element
export function HeroPencil(props: IconProps): JSX.Element
export function HeroPercentBadge(props: IconProps): JSX.Element
export function HeroPhoneArrowDownLeft(props: IconProps): JSX.Element
export function HeroPhoneArrowUpRight(props: IconProps): JSX.Element
export function HeroPhoneXMark(props: IconProps): JSX.Element
export function HeroPhone(props: IconProps): JSX.Element
export function HeroPhoto(props: IconProps): JSX.Element
export function HeroPlayCircle(props: IconProps): JSX.Element
export function HeroPlayPause(props: IconProps): JSX.Element
export function HeroPlay(props: IconProps): JSX.Element
export function HeroPlusCircle(props: IconProps): JSX.Element
export function HeroPlusSmall(props: IconProps): JSX.Element
export function HeroPlus(props: IconProps): JSX.Element
export function HeroPower(props: IconProps): JSX.Element
export function HeroPresentationChartBar(props: IconProps): JSX.Element
export function HeroPresentationChartLine(props: IconProps): JSX.Element
export function HeroPrinter(props: IconProps): JSX.Element
export function HeroPuzzlePiece(props: IconProps): JSX.Element
export function HeroQrCode(props: IconProps): JSX.Element
export function HeroQuestionMarkCircle(props: IconProps): JSX.Element
export function HeroQueueList(props: IconProps): JSX.Element
export function HeroRadio(props: IconProps): JSX.Element
export function HeroReceiptPercent(props: IconProps): JSX.Element
export function HeroReceiptRefund(props: IconProps): JSX.Element
export function HeroRectangleGroup(props: IconProps): JSX.Element
export function HeroRectangleStack(props: IconProps): JSX.Element
export function HeroRocketLaunch(props: IconProps): JSX.Element
export function HeroRss(props: IconProps): JSX.Element
export function HeroScale(props: IconProps): JSX.Element
export function HeroScissors(props: IconProps): JSX.Element
export function HeroServerStack(props: IconProps): JSX.Element
export function HeroServer(props: IconProps): JSX.Element
export function HeroShare(props: IconProps): JSX.Element
export function HeroShieldCheck(props: IconProps): JSX.Element
export function HeroShieldExclamation(props: IconProps): JSX.Element
export function HeroShoppingBag(props: IconProps): JSX.Element
export function HeroShoppingCart(props: IconProps): JSX.Element
export function HeroSignalSlash(props: IconProps): JSX.Element
export function HeroSignal(props: IconProps): JSX.Element
export function HeroSlash(props: IconProps): JSX.Element
export function HeroSparkles(props: IconProps): JSX.Element
export function HeroSpeakerWave(props: IconProps): JSX.Element
export function HeroSpeakerXMark(props: IconProps): JSX.Element
export function HeroSquare2Stack(props: IconProps): JSX.Element
export function HeroSquare3Stack3d(props: IconProps): JSX.Element
export function HeroSquares2x2(props: IconProps): JSX.Element
export function HeroSquaresPlus(props: IconProps): JSX.Element
export function HeroStar(props: IconProps): JSX.Element
export function HeroStopCircle(props: IconProps): JSX.Element
export function HeroStop(props: IconProps): JSX.Element
export function HeroStrikethrough(props: IconProps): JSX.Element
export function HeroSun(props: IconProps): JSX.Element
export function HeroSwatch(props: IconProps): JSX.Element
export function HeroTableCells(props: IconProps): JSX.Element
export function HeroTag(props: IconProps): JSX.Element
export function HeroTicket(props: IconProps): JSX.Element
export function HeroTrash(props: IconProps): JSX.Element
export function HeroTrophy(props: IconProps): JSX.Element
export function HeroTruck(props: IconProps): JSX.Element
export function HeroTv(props: IconProps): JSX.Element
export function HeroUnderline(props: IconProps): JSX.Element
export function HeroUserCircle(props: IconProps): JSX.Element
export function HeroUserGroup(props: IconProps): JSX.Element
export function HeroUserMinus(props: IconProps): JSX.Element
export function HeroUserPlus(props: IconProps): JSX.Element
export function HeroUser(props: IconProps): JSX.Element
export function HeroUsers(props: IconProps): JSX.Element
export function HeroVariable(props: IconProps): JSX.Element
export function HeroVideoCameraSlash(props: IconProps): JSX.Element
export function HeroVideoCamera(props: IconProps): JSX.Element
export function HeroViewColumns(props: IconProps): JSX.Element
export function HeroViewfinderCircle(props: IconProps): JSX.Element
export function HeroWallet(props: IconProps): JSX.Element
export function HeroWifi(props: IconProps): JSX.Element
export function HeroWindow(props: IconProps): JSX.Element
export function HeroWrenchScrewdriver(props: IconProps): JSX.Element
export function HeroWrench(props: IconProps): JSX.Element
export function HeroXCircle(props: IconProps): JSX.Element
export function HeroXMark(props: IconProps): JSX.Element
