// AUTO-GENERATED FILE. DO NOT EDIT BY HAND.
// Icon set: zondicons | License: MIT (MIT_URL)
import type { JSX } from 'solid-js'
import type { IconProps } from './/types'

export function ZondiconAddOutline(props: IconProps): JSX.Element
export function ZondiconAddSolid(props: IconProps): JSX.Element
export function ZondiconAdjust(props: IconProps): JSX.Element
export function ZondiconAirplane(props: IconProps): JSX.Element
export function ZondiconAlbum(props: IconProps): JSX.Element
export function ZondiconAlignCenter(props: IconProps): JSX.Element
export function ZondiconAlignJustified(props: IconProps): JSX.Element
export function ZondiconAlignLeft(props: IconProps): JSX.Element
export function ZondiconAlignRight(props: IconProps): JSX.Element
export function ZondiconAnchor(props: IconProps): JSX.Element
export function ZondiconAnnouncement(props: IconProps): JSX.Element
export function ZondiconApparel(props: IconProps): JSX.Element
export function ZondiconArrowDown(props: IconProps): JSX.Element
export function ZondiconArrowLeft(props: IconProps): JSX.Element
export function ZondiconArrowOutlineDown(props: IconProps): JSX.Element
export function ZondiconArrowOutlineLeft(props: IconProps): JSX.Element
export function ZondiconArrowOutlineRight(props: IconProps): JSX.Element
export function ZondiconArrowOutlineUp(props: IconProps): JSX.Element
export function ZondiconArrowRight(props: IconProps): JSX.Element
export function ZondiconArrowThickDown(props: IconProps): JSX.Element
export function ZondiconArrowThickLeft(props: IconProps): JSX.Element
export function ZondiconArrowThickRight(props: IconProps): JSX.Element
export function ZondiconArrowThickUp(props: IconProps): JSX.Element
export function ZondiconArrowThinDown(props: IconProps): JSX.Element
export function ZondiconArrowThinLeft(props: IconProps): JSX.Element
export function ZondiconArrowThinRight(props: IconProps): JSX.Element
export function ZondiconArrowThinUp(props: IconProps): JSX.Element
export function ZondiconArrowUp(props: IconProps): JSX.Element
export function ZondiconArtist(props: IconProps): JSX.Element
export function ZondiconAtSymbol(props: IconProps): JSX.Element
export function ZondiconAttachment(props: IconProps): JSX.Element
export function ZondiconBackspace(props: IconProps): JSX.Element
export function ZondiconBackwardStep(props: IconProps): JSX.Element
export function ZondiconBackward(props: IconProps): JSX.Element
export function ZondiconBadge(props: IconProps): JSX.Element
export function ZondiconBatteryFull(props: IconProps): JSX.Element
export function ZondiconBatteryHalf(props: IconProps): JSX.Element
export function ZondiconBatteryLow(props: IconProps): JSX.Element
export function ZondiconBeverage(props: IconProps): JSX.Element
export function ZondiconBlock(props: IconProps): JSX.Element
export function ZondiconBluetooth(props: IconProps): JSX.Element
export function ZondiconBolt(props: IconProps): JSX.Element
export function ZondiconBookReference(props: IconProps): JSX.Element
export function ZondiconBookmarkCopy2(props: IconProps): JSX.Element
export function ZondiconBookmarkCopy3(props: IconProps): JSX.Element
export function ZondiconBookmarkOutlineAdd(props: IconProps): JSX.Element
export function ZondiconBookmarkOutline(props: IconProps): JSX.Element
export function ZondiconBookmark(props: IconProps): JSX.Element
export function ZondiconBorderAll(props: IconProps): JSX.Element
export function ZondiconBorderBottom(props: IconProps): JSX.Element
export function ZondiconBorderHorizontal(props: IconProps): JSX.Element
export function ZondiconBorderInner(props: IconProps): JSX.Element
export function ZondiconBorderLeft(props: IconProps): JSX.Element
export function ZondiconBorderNone(props: IconProps): JSX.Element
export function ZondiconBorderOuter(props: IconProps): JSX.Element
export function ZondiconBorderRight(props: IconProps): JSX.Element
export function ZondiconBorderTop(props: IconProps): JSX.Element
export function ZondiconBorderVertical(props: IconProps): JSX.Element
export function ZondiconBox(props: IconProps): JSX.Element
export function ZondiconBrightnessDown(props: IconProps): JSX.Element
export function ZondiconBrightnessUp(props: IconProps): JSX.Element
export function ZondiconBrowserWindowNew(props: IconProps): JSX.Element
export function ZondiconBrowserWindowOpen(props: IconProps): JSX.Element
export function ZondiconBrowserWindow(props: IconProps): JSX.Element
export function ZondiconBug(props: IconProps): JSX.Element
export function ZondiconBuoy(props: IconProps): JSX.Element
export function ZondiconCalculator(props: IconProps): JSX.Element
export function ZondiconCalendar(props: IconProps): JSX.Element
export function ZondiconCamera(props: IconProps): JSX.Element
export function ZondiconChartBar(props: IconProps): JSX.Element
export function ZondiconChartPie(props: IconProps): JSX.Element
export function ZondiconChart(props: IconProps): JSX.Element
export function ZondiconChatBubbleDots(props: IconProps): JSX.Element
export function ZondiconCheckmarkOutline(props: IconProps): JSX.Element
export function ZondiconCheckmark(props: IconProps): JSX.Element
export function ZondiconCheveronDown(props: IconProps): JSX.Element
export function ZondiconCheveronLeft(props: IconProps): JSX.Element
export function ZondiconCheveronOutlineDown(props: IconProps): JSX.Element
export function ZondiconCheveronOutlineLeft(props: IconProps): JSX.Element
export function ZondiconCheveronOutlineRight(props: IconProps): JSX.Element
export function ZondiconCheveronOutlineUp(props: IconProps): JSX.Element
export function ZondiconCheveronRight(props: IconProps): JSX.Element
export function ZondiconCheveronUp(props: IconProps): JSX.Element
export function ZondiconClipboard(props: IconProps): JSX.Element
export function ZondiconCloseOutline(props: IconProps): JSX.Element
export function ZondiconCloseSolid(props: IconProps): JSX.Element
export function ZondiconClose(props: IconProps): JSX.Element
export function ZondiconCloudUpload(props: IconProps): JSX.Element
export function ZondiconCloud(props: IconProps): JSX.Element
export function ZondiconCode(props: IconProps): JSX.Element
export function ZondiconCoffee(props: IconProps): JSX.Element
export function ZondiconCog(props: IconProps): JSX.Element
export function ZondiconColorPalette(props: IconProps): JSX.Element
export function ZondiconCompose(props: IconProps): JSX.Element
export function ZondiconComputerDesktop(props: IconProps): JSX.Element
export function ZondiconComputerLaptop(props: IconProps): JSX.Element
export function ZondiconConversation(props: IconProps): JSX.Element
export function ZondiconCopy(props: IconProps): JSX.Element
export function ZondiconCreditCard(props: IconProps): JSX.Element
export function ZondiconCurrencyDollar(props: IconProps): JSX.Element
export function ZondiconDashboard(props: IconProps): JSX.Element
export function ZondiconDateAdd(props: IconProps): JSX.Element
export function ZondiconDialPad(props: IconProps): JSX.Element
export function ZondiconDirections(props: IconProps): JSX.Element
export function ZondiconDocumentAdd(props: IconProps): JSX.Element
export function ZondiconDocument(props: IconProps): JSX.Element
export function ZondiconDotsHorizontalDouble(props: IconProps): JSX.Element
export function ZondiconDotsHorizontalTriple(props: IconProps): JSX.Element
export function ZondiconDownload(props: IconProps): JSX.Element
export function ZondiconDuplicate(props: IconProps): JSX.Element
export function ZondiconEditCopy(props: IconProps): JSX.Element
export function ZondiconEditCrop(props: IconProps): JSX.Element
export function ZondiconEditCut(props: IconProps): JSX.Element
export function ZondiconEditPencil(props: IconProps): JSX.Element
export function ZondiconEducation(props: IconProps): JSX.Element
export function ZondiconEnvelope(props: IconProps): JSX.Element
export function ZondiconExclamationOutline(props: IconProps): JSX.Element
export function ZondiconExclamationSolid(props: IconProps): JSX.Element
export function ZondiconExplore(props: IconProps): JSX.Element
export function ZondiconFactory(props: IconProps): JSX.Element
export function ZondiconFastForward(props: IconProps): JSX.Element
export function ZondiconFastRewind(props: IconProps): JSX.Element
export function ZondiconFilm(props: IconProps): JSX.Element
export function ZondiconFilter(props: IconProps): JSX.Element
export function ZondiconFlag(props: IconProps): JSX.Element
export function ZondiconFlashlight(props: IconProps): JSX.Element
export function ZondiconFolderOutlineAdd(props: IconProps): JSX.Element
export function ZondiconFolderOutline(props: IconProps): JSX.Element
export function ZondiconFolder(props: IconProps): JSX.Element
export function ZondiconFormatBold(props: IconProps): JSX.Element
export function ZondiconFormatFontSize(props: IconProps): JSX.Element
export function ZondiconFormatItalic(props: IconProps): JSX.Element
export function ZondiconFormatTextSize(props: IconProps): JSX.Element
export function ZondiconFormatUnderline(props: IconProps): JSX.Element
export function ZondiconForwardStep(props: IconProps): JSX.Element
export function ZondiconForward(props: IconProps): JSX.Element
export function ZondiconGift(props: IconProps): JSX.Element
export function ZondiconGlobe(props: IconProps): JSX.Element
export function ZondiconHandStop(props: IconProps): JSX.Element
export function ZondiconHardDrive(props: IconProps): JSX.Element
export function ZondiconHeadphones(props: IconProps): JSX.Element
export function ZondiconHeart(props: IconProps): JSX.Element
export function ZondiconHome(props: IconProps): JSX.Element
export function ZondiconHot(props: IconProps): JSX.Element
export function ZondiconHourGlass(props: IconProps): JSX.Element
export function ZondiconInboxCheck(props: IconProps): JSX.Element
export function ZondiconInboxDownload(props: IconProps): JSX.Element
export function ZondiconInboxFull(props: IconProps): JSX.Element
export function ZondiconInbox(props: IconProps): JSX.Element
export function ZondiconIndentDecrease(props: IconProps): JSX.Element
export function ZondiconIndentIncrease(props: IconProps): JSX.Element
export function ZondiconInformationOutline(props: IconProps): JSX.Element
export function ZondiconInformationSolid(props: IconProps): JSX.Element
export function ZondiconKey(props: IconProps): JSX.Element
export function ZondiconKeyboard(props: IconProps): JSX.Element
export function ZondiconLayers(props: IconProps): JSX.Element
export function ZondiconLibrary(props: IconProps): JSX.Element
export function ZondiconLightBulb(props: IconProps): JSX.Element
export function ZondiconLink(props: IconProps): JSX.Element
export function ZondiconListAdd(props: IconProps): JSX.Element
export function ZondiconListBullet(props: IconProps): JSX.Element
export function ZondiconList(props: IconProps): JSX.Element
export function ZondiconLoadBalancer(props: IconProps): JSX.Element
export function ZondiconLocationCurrent(props: IconProps): JSX.Element
export function ZondiconLocationFood(props: IconProps): JSX.Element
export function ZondiconLocationGasStation(props: IconProps): JSX.Element
export function ZondiconLocationHotel(props: IconProps): JSX.Element
export function ZondiconLocationMarina(props: IconProps): JSX.Element
export function ZondiconLocationPark(props: IconProps): JSX.Element
export function ZondiconLocationRestroom(props: IconProps): JSX.Element
export function ZondiconLocationShopping(props: IconProps): JSX.Element
export function ZondiconLocation(props: IconProps): JSX.Element
export function ZondiconLockClosed(props: IconProps): JSX.Element
export function ZondiconLockOpen(props: IconProps): JSX.Element
export function ZondiconMap(props: IconProps): JSX.Element
export function ZondiconMenu(props: IconProps): JSX.Element
export function ZondiconMic(props: IconProps): JSX.Element
export function ZondiconMinusOutline(props: IconProps): JSX.Element
export function ZondiconMinusSolid(props: IconProps): JSX.Element
export function ZondiconMobileDevices(props: IconProps): JSX.Element
export function ZondiconMoodHappyOutline(props: IconProps): JSX.Element
export function ZondiconMoodHappySolid(props: IconProps): JSX.Element
export function ZondiconMoodNeutralOutline(props: IconProps): JSX.Element
export function ZondiconMoodNeutralSolid(props: IconProps): JSX.Element
export function ZondiconMoodSadOutline(props: IconProps): JSX.Element
export function ZondiconMoodSadSolid(props: IconProps): JSX.Element
export function ZondiconMouse(props: IconProps): JSX.Element
export function ZondiconMusicAlbum(props: IconProps): JSX.Element
export function ZondiconMusicArtist(props: IconProps): JSX.Element
export function ZondiconMusicNotes(props: IconProps): JSX.Element
export function ZondiconMusicPlaylist(props: IconProps): JSX.Element
export function ZondiconNavigationMore(props: IconProps): JSX.Element
export function ZondiconNetwork(props: IconProps): JSX.Element
export function ZondiconNewsPaper(props: IconProps): JSX.Element
export function ZondiconNotification(props: IconProps): JSX.Element
export function ZondiconNotificationsOutline(props: IconProps): JSX.Element
export function ZondiconNotifications(props: IconProps): JSX.Element
export function ZondiconPaste(props: IconProps): JSX.Element
export function ZondiconPauseOutline(props: IconProps): JSX.Element
export function ZondiconPauseSolid(props: IconProps): JSX.Element
export function ZondiconPause(props: IconProps): JSX.Element
export function ZondiconPenTool(props: IconProps): JSX.Element
export function ZondiconPhone(props: IconProps): JSX.Element
export function ZondiconPhoto(props: IconProps): JSX.Element
export function ZondiconPhpElephant(props: IconProps): JSX.Element
export function ZondiconPin(props: IconProps): JSX.Element
export function ZondiconPlayOutline(props: IconProps): JSX.Element
export function ZondiconPlay(props: IconProps): JSX.Element
export function ZondiconPlaylist(props: IconProps): JSX.Element
export function ZondiconPlugin(props: IconProps): JSX.Element
export function ZondiconPortfolio(props: IconProps): JSX.Element
export function ZondiconPrinter(props: IconProps): JSX.Element
export function ZondiconPylon(props: IconProps): JSX.Element
export function ZondiconQuestion(props: IconProps): JSX.Element
export function ZondiconQueue(props: IconProps): JSX.Element
export function ZondiconRadarCopy2(props: IconProps): JSX.Element
export function ZondiconRadar(props: IconProps): JSX.Element
export function ZondiconRadio(props: IconProps): JSX.Element
export function ZondiconRefresh(props: IconProps): JSX.Element
export function ZondiconReload(props: IconProps): JSX.Element
export function ZondiconReplyAll(props: IconProps): JSX.Element
export function ZondiconReply(props: IconProps): JSX.Element
export function ZondiconRepost(props: IconProps): JSX.Element
export function ZondiconSaveDisk(props: IconProps): JSX.Element
export function ZondiconScreenFull(props: IconProps): JSX.Element
export function ZondiconSearch(props: IconProps): JSX.Element
export function ZondiconSend(props: IconProps): JSX.Element
export function ZondiconServers(props: IconProps): JSX.Element
export function ZondiconShare01(props: IconProps): JSX.Element
export function ZondiconShareAlt(props: IconProps): JSX.Element
export function ZondiconShare(props: IconProps): JSX.Element
export function ZondiconShield(props: IconProps): JSX.Element
export function ZondiconShoppingCart(props: IconProps): JSX.Element
export function ZondiconShowSidebar(props: IconProps): JSX.Element
export function ZondiconShuffle(props: IconProps): JSX.Element
export function ZondiconStandBy(props: IconProps): JSX.Element
export function ZondiconStarFull(props: IconProps): JSX.Element
export function ZondiconStation(props: IconProps): JSX.Element
export function ZondiconStepBackward(props: IconProps): JSX.Element
export function ZondiconStepForward(props: IconProps): JSX.Element
export function ZondiconStethoscope(props: IconProps): JSX.Element
export function ZondiconStoreFront(props: IconProps): JSX.Element
export function ZondiconStrokeWidth(props: IconProps): JSX.Element
export function ZondiconSubdirectoryLeft(props: IconProps): JSX.Element
export function ZondiconSubdirectoryRight(props: IconProps): JSX.Element
export function ZondiconSwap(props: IconProps): JSX.Element
export function ZondiconTablet(props: IconProps): JSX.Element
export function ZondiconTag(props: IconProps): JSX.Element
export function ZondiconTarget(props: IconProps): JSX.Element
export function ZondiconTextBox(props: IconProps): JSX.Element
export function ZondiconTextDecoration(props: IconProps): JSX.Element
export function ZondiconThermometer(props: IconProps): JSX.Element
export function ZondiconThumbsDown(props: IconProps): JSX.Element
export function ZondiconThumbsUp(props: IconProps): JSX.Element
export function ZondiconTicket(props: IconProps): JSX.Element
export function ZondiconTime(props: IconProps): JSX.Element
export function ZondiconTimer(props: IconProps): JSX.Element
export function ZondiconToolsCopy(props: IconProps): JSX.Element
export function ZondiconTranslate(props: IconProps): JSX.Element
export function ZondiconTrash(props: IconProps): JSX.Element
export function ZondiconTravelBus(props: IconProps): JSX.Element
export function ZondiconTravelCar(props: IconProps): JSX.Element
export function ZondiconTravelCase(props: IconProps): JSX.Element
export function ZondiconTravelTaxiCab(props: IconProps): JSX.Element
export function ZondiconTravelTrain(props: IconProps): JSX.Element
export function ZondiconTravelWalk(props: IconProps): JSX.Element
export function ZondiconTravel(props: IconProps): JSX.Element
export function ZondiconTrophy(props: IconProps): JSX.Element
export function ZondiconTuning(props: IconProps): JSX.Element
export function ZondiconUpload(props: IconProps): JSX.Element
export function ZondiconUsb(props: IconProps): JSX.Element
export function ZondiconUserAdd(props: IconProps): JSX.Element
export function ZondiconUserGroup(props: IconProps): JSX.Element
export function ZondiconUserSolidCircle(props: IconProps): JSX.Element
export function ZondiconUserSolidSquare(props: IconProps): JSX.Element
export function ZondiconUser(props: IconProps): JSX.Element
export function ZondiconVector(props: IconProps): JSX.Element
export function ZondiconVideoCamera(props: IconProps): JSX.Element
export function ZondiconViewCarousel(props: IconProps): JSX.Element
export function ZondiconViewColumn(props: IconProps): JSX.Element
export function ZondiconViewHide(props: IconProps): JSX.Element
export function ZondiconViewList(props: IconProps): JSX.Element
export function ZondiconViewShow(props: IconProps): JSX.Element
export function ZondiconViewTile(props: IconProps): JSX.Element
export function ZondiconVolumeDown(props: IconProps): JSX.Element
export function ZondiconVolumeMute(props: IconProps): JSX.Element
export function ZondiconVolumeOff(props: IconProps): JSX.Element
export function ZondiconVolumeUp(props: IconProps): JSX.Element
export function ZondiconWallet(props: IconProps): JSX.Element
export function ZondiconWatch(props: IconProps): JSX.Element
export function ZondiconWindowNew(props: IconProps): JSX.Element
export function ZondiconWindowOpen(props: IconProps): JSX.Element
export function ZondiconWindow(props: IconProps): JSX.Element
export function ZondiconWrench(props: IconProps): JSX.Element
export function ZondiconYinYang(props: IconProps): JSX.Element
export function ZondiconZoomIn(props: IconProps): JSX.Element
export function ZondiconZoomOut(props: IconProps): JSX.Element
